# Table of Content:
* [Li Yuan's second week work](#2)
* [Li Yuan's third week work](#3)
    * [Pandas convert](#31)
    * [MdTraj convert](#32)
* [Li Yuan's forth week work](#4)
    * [get_all_atom() function](#41)
    * [get_atom_and_hetatm() function](#42)
    * [PDB Class](#43)
    * [An example of this class "4lza"](#44)
* [Li Yuan's fifth week work](#5)
    * [get_general_table()](#51)
    * [get_atom_hetatm_table()](#52)
    * [Test 100 pdb files and merge them into one](#53)
    * [Remark: Bug Fix to get_missing_residue() function](#54)
    * [Merge 100 atom and hetatm tables and test the time](#55)
    * [Test the overall time when merging 100 atom and general tables](#56)
    * [Test average processing time of one pdf file in 100 random pdb files](#57)
* [Li Yuan's sixth - eighth week work](#6)
    * [The estimated time of extracting all tables of 170k pdb file](#61)
    * [Handling with None Type pdb files](#62)
    * [added some warning messages to deal with some exceptions in each desired field](#63)
    * [Check process and my suggestion on not going on this problem](#64)
* [Li Yuan first winter break work](#7)
    * [Get FASTA Sequence](#71)
    * [Get Missing Residue Index: colors – yellow/grey](#72)
    * [Get Entity IDs – Entity ID1, Entity ID2,…](#73)
    * [Get Global Stoichiometry: Homo 2-mer - A2](#74)
    * [Get Mutation: Y/N](#75)
    * [Get number of sequences in pdb](#76)
    * [Add all these new info into general tables](#77)

<a id='2'></a>
# Li Yuan's second week work 

This is a set of basic examples of the usage and outputs of the various individual functions included in. There are generally three types of functions:

+ Functions that perform searches and return lists of PDB IDs
+ Functions that get information about specific PDB IDs
+ Other general-purpose lookup functions

The list of supported search types, as well as the different types of information that can be returned for a given PDB ID, is large (and growing) and is enumerated in the docstrings of pypdb.py. The PDB allows a very wide range of different types of queries, and so any option that is not currently available can likely be implemented based on the structure of the query types that have already been implemented. Please submit feedback and pull requests on GitHub.

### I didn't find any funcion in that package pypdb we can use to extract seqres and atom, so I only use get_pdb_file() function from that package to get the file and write my own function to do that.

### Preamble

We import this package pypdb and prepare some other things.

In [1]:
%pylab inline
from IPython.display import HTML

## Import from local directory
import sys
sys.path.insert(0, '../pypdb')
from pypdb import *

## Import from installed package
# from pypdb import *

import pprint

%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib

## This function I wrote is to extract only the seqres as a list

In [2]:
def get_seqres(pdb_id):
    """ Return the seqres sequence of a pdb file
    
    >>> get_seqres('4Z0L')
    >>> get_seqres('4lza')
    """
    pdb_file = get_pdb_file(pdb_id, filetype='pdb', compression=False) 
    # using a get_pdb_file() function from pypdb package to return a file with format 'pdb'.
    file1 = pdb_file.splitlines()
    # split this long string into list by \n.
    list_se = []
    for line in file1:
        if line[:6] == "SEQRES":
            list_se.append(line)
    return(list_se)

In [3]:
get_seqres('4lza')[:10]

['SEQRES   1 A  195  MSE HIS HIS HIS HIS HIS HIS SER SER GLY VAL ASP LEU          ',
 'SEQRES   2 A  195  GLY THR GLU ASN LEU TYR PHE GLN SER MSE THR LEU GLU          ',
 'SEQRES   3 A  195  GLU ILE LYS MSE MSE ILE ARG GLU ILE PRO ASP PHE PRO          ',
 'SEQRES   4 A  195  LYS LYS GLY ILE LYS PHE LYS ASP ILE THR PRO VAL LEU          ',
 'SEQRES   5 A  195  LYS ASP ALA LYS ALA PHE ASN TYR SER ILE GLU MSE LEU          ',
 'SEQRES   6 A  195  ALA LYS ALA LEU GLU GLY ARG LYS PHE ASP LEU ILE ALA          ',
 'SEQRES   7 A  195  ALA PRO GLU ALA ARG GLY PHE LEU PHE GLY ALA PRO LEU          ',
 'SEQRES   8 A  195  ALA TYR ARG LEU GLY VAL GLY PHE VAL PRO VAL ARG LYS          ',
 'SEQRES   9 A  195  PRO GLY LYS LEU PRO ALA GLU THR LEU SER TYR GLU TYR          ',
 'SEQRES  10 A  195  GLU LEU GLU TYR GLY THR ASP SER LEU GLU ILE HIS LYS          ']

In [4]:
get_seqres('4Z0L')[:20]

['SEQRES   1 A  587  ALA ASN PRO CYS CYS SER ASN PRO CYS GLN ASN ARG GLY          ',
 'SEQRES   2 A  587  GLU CYS MET SER THR GLY PHE ASP GLN TYR LYS CYS ASP          ',
 'SEQRES   3 A  587  CYS THR ARG THR GLY PHE TYR GLY GLU ASN CYS THR THR          ',
 'SEQRES   4 A  587  PRO GLU PHE LEU THR ARG ILE LYS LEU LEU LEU LYS PRO          ',
 'SEQRES   5 A  587  THR PRO ASN THR VAL HIS TYR ILE LEU THR HIS PHE LYS          ',
 'SEQRES   6 A  587  GLY VAL TRP ASN ILE VAL ASN ASN ILE PRO PHE LEU ARG          ',
 'SEQRES   7 A  587  SER LEU ILE MET LYS TYR VAL LEU THR SER ARG SER TYR          ',
 'SEQRES   8 A  587  LEU ILE ASP SER PRO PRO THR TYR ASN VAL HIS TYR GLY          ',
 'SEQRES   9 A  587  TYR LYS SER TRP GLU ALA PHE SER ASN LEU SER TYR TYR          ',
 'SEQRES  10 A  587  THR ARG ALA LEU PRO PRO VAL ALA ASP ASP CYS PRO THR          ',
 'SEQRES  11 A  587  PRO MET GLY VAL LYS GLY ASN LYS GLU LEU PRO ASP SER          ',
 'SEQRES  12 A  587  LYS GLU VAL LEU GLU LYS VAL LEU LEU ARG ARG GLU PHE          ',
 'SEQRES  13 A  587  ILE PRO ASP PRO GLN GLY SER ASN MET MET PHE ALA PHE          ',
 'SEQRES  14 A  587  PHE ALA GLN HIS PHE THR HIS GLN PHE PHE LYS THR ASP          ',
 'SEQRES  15 A  587  HIS LYS ARG GLY PRO GLY PHE THR ARG GLY LEU GLY HIS          ',
 'SEQRES  16 A  587  GLY VAL ASP LEU ASN HIS ILE TYR GLY GLU THR LEU ASP          ',
 'SEQRES  17 A  587  ARG GLN HIS LYS LEU ARG LEU PHE LYS ASP GLY LYS LEU          ',
 'SEQRES  18 A  587  LYS TYR GLN VAL ILE GLY GLY GLU VAL TYR PRO PRO THR          ',
 'SEQRES  19 A  587  VAL LYS ASP THR GLN VAL GLU MET ILE TYR PRO PRO HIS          ',
 'SEQRES  20 A  587  ILE PRO GLU ASN LEU GLN PHE ALA VAL GLY GLN GLU VAL          ']

### This function I wrote is to extract only the atom sequence as a list

In [5]:
def get_atom(pdb_id):
    """ Return the atom sequence of a pdb file
    
    >>> get_atom('4Z0L')
    >>> get_atom('4lza')
    """
    pdb_file = get_pdb_file(pdb_id, filetype='pdb', compression=False)
    # using a get_pdb_file() function from pypdb package to return a file with format 'pdb'.
    file1 = pdb_file.splitlines()
    list_atom = []
    for line in file1:
        if line[:4] == "ATOM":
            list_atom.append(line)
    return(list_atom)

In [6]:
get_atom('4Z0L')[:10]

['ATOM      1  N   ALA A  33     113.744  17.524  85.910  1.00 75.99           N  ',
 'ATOM      2  CA  ALA A  33     114.749  17.116  86.884  1.00 76.70           C  ',
 'ATOM      3  C   ALA A  33     115.677  18.275  87.231  1.00 73.52           C  ',
 'ATOM      4  O   ALA A  33     116.176  18.367  88.354  1.00 75.48           O  ',
 'ATOM      5  CB  ALA A  33     115.548  15.934  86.358  1.00 78.19           C  ',
 'ATOM      6  N   ASN A  34     115.906  19.154  86.261  1.00 67.98           N  ',
 'ATOM      7  CA  ASN A  34     116.747  20.327  86.469  1.00 63.43           C  ',
 'ATOM      8  C   ASN A  34     116.113  21.264  87.492  1.00 60.58           C  ',
 'ATOM      9  O   ASN A  34     115.006  21.756  87.287  1.00 61.30           O  ',
 'ATOM     10  CB  ASN A  34     116.983  21.058  85.144  1.00 63.09           C  ']

In [7]:
get_atom('4lza')[:10]

['ATOM      1  N   THR A   0     -27.785   5.217 -21.426  1.00 50.53           N  ',
 'ATOM      2  CA  THR A   0     -27.459   5.049 -19.974  1.00 49.41           C  ',
 'ATOM      3  C   THR A   0     -25.949   5.130 -19.667  1.00 46.13           C  ',
 'ATOM      4  O   THR A   0     -25.572   5.789 -18.699  1.00 44.22           O  ',
 'ATOM      5  CB  THR A   0     -28.153   3.815 -19.346  1.00 51.85           C  ',
 'ATOM      6  OG1 THR A   0     -27.919   3.787 -17.932  1.00 52.21           O  ',
 'ATOM      7  CG2 THR A   0     -27.688   2.516 -19.989  1.00 53.52           C  ',
 'ATOM      8  N   LEU A   1     -25.087   4.511 -20.480  1.00 43.20           N  ',
 'ATOM      9  CA  LEU A   1     -23.681   4.942 -20.481  1.00 42.39           C  ',
 'ATOM     10  C   LEU A   1     -23.615   6.356 -21.059  1.00 43.21           C  ']

<a id='3'></a>
# Li Yuan's third week work

<a id='31'></a>
## We first used pandas to convert a list into dataframe

### First we used split() to split each string in the list returned by get_atom() function

In [8]:
import pandas as pd

In [9]:
def get_atom(pdb_id):
    """ Return the atom sequence of a pdb file as a pandas dataframe
    
    >>> get_atom('4Z0L')
    >>> get_atom('4lza')
    """
    pdb_file = get_pdb_file(pdb_id, filetype='pdb', compression=False)
    # using a get_pdb_file() function from pypdb package to return a file with format 'pdb'.
    file1 = pdb_file.splitlines()
    list_atom = []
    for line in file1:
        if line[:4] == "ATOM":
            list_atom.append(line)
    list_s_atom = [s.split() for s in list_atom]
    # split each string in a list by white spaces
    df = pd.DataFrame(list_s_atom)
    # use DataFrame function to convert a list to dataframe
    df["id"] = pdb_id
    # add one id column to exsiting dataframe
    return(df)

In [10]:
get_atom("4lza").head(11)

       0   1    2    3  4  5        6      7        8     9     10 11    id
0   ATOM   1    N  THR  A  0  -27.785  5.217  -21.426  1.00  50.53  N  4lza
1   ATOM   2   CA  THR  A  0  -27.459  5.049  -19.974  1.00  49.41  C  4lza
2   ATOM   3    C  THR  A  0  -25.949  5.130  -19.667  1.00  46.13  C  4lza
3   ATOM   4    O  THR  A  0  -25.572  5.789  -18.699  1.00  44.22  O  4lza
4   ATOM   5   CB  THR  A  0  -28.153  3.815  -19.346  1.00  51.85  C  4lza
5   ATOM   6  OG1  THR  A  0  -27.919  3.787  -17.932  1.00  52.21  O  4lza
6   ATOM   7  CG2  THR  A  0  -27.688  2.516  -19.989  1.00  53.52  C  4lza
7   ATOM   8    N  LEU  A  1  -25.087  4.511  -20.480  1.00  43.20  N  4lza
8   ATOM   9   CA  LEU  A  1  -23.681  4.942  -20.481  1.00  42.39  C  4lza
9   ATOM  10    C  LEU  A  1  -23.615  6.356  -21.059  1.00  43.21  C  4lza
10  ATOM  11    O  LEU  A  1  -22.738  7.137  -20.688  1.00  41.35  O  4lza

## Second we want to put a couple of pdb entries into one dataframe.

In [11]:
def get_some_atom(L):
    """ Take a list with returning some atom parts of pdb files into one dataframe 
    
    >>> get_some_atom(["4lza", "4Z0L"])
    """
    frames = [get_atom(l) for l in L]
    return(pd.concat(frames))

## We test this function with a list ["4lza", "4Z0L]

In [12]:
get_some_atom(["4lza", "4Z0L"])

,0,1,2,3,4,5,6,7,8,9,10,11,id
0,ATOM,1,N,THR,A,0,-27.785,5.217,-21.426,1.00,50.53,N,4lza
1,ATOM,2,CA,THR,A,0,-27.459,5.049,-19.974,1.00,49.41,C,4lza
2,ATOM,3,C,THR,A,0,-25.949,5.130,-19.667,1.00,46.13,C,4lza
3,ATOM,4,O,THR,A,0,-25.572,5.789,-18.699,1.00,44.22,O,4lza
4,ATOM,5,CB,THR,A,0,-28.153,3.815,-19.346,1.00,51.85,C,4lza
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17887,ATOM,17891,C,VAL,D,582,109.996,36.082,25.066,1.00,44.77,C,4Z0L
17888,ATOM,17892,O,VAL,D,582,110.051,34.970,25.592,1.00,45.92,O,4Z0L
17889,ATOM,17893,CB,VAL,D,582,109.039,36.239,22.764,1.00,45.04,C,4Z0L
17890,ATOM,17894,CG1,VAL,D,582,109.314,36.646,21.323,1.00,40.74,C,4Z0L
17891,ATOM,17895,CG2,VAL,D,582,108.404,34.858,22.819,1.00,47.16,C,4Z0L

## Next we want to put all ids into one dataframe

### We used get_all() to list all pdb entries.

# The webpage we are requesting is not available.
# Legacy Search API Web Service will be shutdown on December 9th, 2020. Queries made to this API endpoints will fail.

len(get_all())

### We found there was 169681 entries in the current PDB  DataBase.

### We used concat() function to merge all the dataframe of each pdb entry into one huge dataframe.

# Legacy Search API Web Service will be shutdown on December 9th, 2020. Queries made to this API endpoints will fail.

frames = [get_atom(id) for id in get_all()[:2]]
pd.concat(frames)

<a id='32'></a>
## We used mdtraj package to load pdb file into memory from URL

>MDTraj is a python library that allows users to manipulate molecular dynamics (MD) trajectories. Features include:
1. Wide MD format support, including pdb, xtc, trr, dcd, binpos, netcdf, mdcrd, prmtop, and more.
2. Extremely fast RMSD calculations (4x the speed of the original Theobald QCP).
3. Extensive analysis functions including those that compute bonds, angles, dihedrals, hydrogen bonds, secondary structure, and NMR observables.
4. Lightweight, Pythonic API.

In [13]:
import mdtraj as md # import this package

In [14]:
pdb = md.load_pdb("https://files.rcsb.org/view/4LZA.pdb")  # load data

In [15]:
print(pdb) # print to see how many frames and atoms, residues this file has

<mdtraj.Trajectory with 1 frames, 2833 atoms, 512 residues, and unitcells>

## We convert this pdb file into topology

In [16]:
topology = pdb.topology

In [17]:
table, bonds = topology.to_dataframe()

In [18]:
print(table.head(7))

   serial name element  resSeq resName  chainID segmentID
0       1    N       N       0     THR        0
1       2   CA       C       0     THR        0
2       3    C       C       0     THR        0
3       4    O       O       0     THR        0
4       5   CB       C       0     THR        0
5       6  OG1       O       0     THR        0
6       7  CG2       C       0     THR        0

In [19]:
topology.atom(10)

LEU1-O

In [20]:
topology.atoms

In [21]:
[i for i in topology.atoms][:10]

[THR0-N,
 THR0-CA,
 THR0-C,
 THR0-O,
 THR0-CB,
 THR0-OG1,
 THR0-CG2,
 LEU1-N,
 LEU1-CA,
 LEU1-C]

In [22]:
print(table.head(10))

   serial name element  resSeq resName  chainID segmentID
0       1    N       N       0     THR        0
1       2   CA       C       0     THR        0
2       3    C       C       0     THR        0
3       4    O       O       0     THR        0
4       5   CB       C       0     THR        0
5       6  OG1       O       0     THR        0
6       7  CG2       C       0     THR        0
7       8    N       N       1     LEU        0
8       9   CA       C       1     LEU        0
9      10    C       C       1     LEU        0

In [23]:
atom = pdb.atom_slice(range(2833))

In [24]:
print(atom)

<mdtraj.Trajectory with 1 frames, 2833 atoms, 512 residues, and unitcells>

In [25]:
atom.xyz

array([[[-2.7785,  0.5217, -2.1426],
        [-2.7459,  0.5049, -1.9974],
        [-2.5949,  0.513 , -1.9667],
        ...,
        [-0.6332, -1.3026, -0.3481],
        [-0.8265, -1.4563, -0.0902],
        [-2.8824,  1.244 , -0.1084]]], dtype=float32)

In [26]:
[i for i in topology.bonds][:10]

[Bond(THR0-CA, THR0-C),
 Bond(THR0-C, THR0-O),
 Bond(THR0-CA, THR0-CB),
 Bond(THR0-N, THR0-CA),
 Bond(THR0-CB, THR0-CG2),
 Bond(THR0-CB, THR0-OG1),
 Bond(THR0-C, LEU1-N),
 Bond(LEU1-CA, LEU1-C),
 Bond(LEU1-C, LEU1-O),
 Bond(LEU1-CA, LEU1-CB)]

<a id='4'></a>
# Li Yuan's forth week work

## This function returns all the atom part, including ATOM, ANISOU, TER
<a id='41'></a>

In [27]:
def get_all_atom(pdb_id):
    """ Return the all atom sequence of a pdb file as a pandas dataframe
    
    >>> get_all_atom('4Z0L')
    >>> get_all_atom('4lza')
    """
    pdb_file = get_pdb_file(pdb_id, filetype='pdb', compression=False)
    # using a get_pdb_file() function from pypdb package to return a file with format 'pdb'.
    file1 = pdb_file.splitlines()
    list_atom = []
    
    # Find the index number of the line with ATOM
    for line in file1:
        if line[:4] == "ATOM":
            num = file1.index(line)
            break
    
    # we add/append all the lines which are within atom part until we meet CONECT
    while file1[num][:6] != "CONECT":
        list_atom.append(file1[num])
        num = num + 1
        
    list_s_atom = [s.split() for s in list_atom]
    # split each string in a list by white spaces
    
    df = pd.DataFrame(list_s_atom)
    # use DataFrame function to convert a list to dataframe
    df["id"] = pdb_id
    # add one id column to exsiting dataframe
    return(df)

In [28]:
get_all_atom("4lza")

,0,1,2,3,4,5,6,7,8,9,10,11,12,id
0,ATOM,1,N,THR,A,0,-27.785,5.217,-21.426,1.00,50.53,N,None,4lza
1,ANISOU,1,N,THR,A,0,6212,6054,6933,75,-219,-115,N,4lza
2,ATOM,2,CA,THR,A,0,-27.459,5.049,-19.974,1.00,49.41,C,None,4lza
3,ANISOU,2,CA,THR,A,0,6089,5870,6816,59,-181,-113,C,4lza
4,ATOM,3,C,THR,A,0,-25.949,5.130,-19.667,1.00,46.13,C,None,4lza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5529,HETATM,2850,O,HOH,B,286,-0.332,17.645,1.000,1.00,42.23,O,None,4lza
5530,HETATM,2851,O,HOH,B,287,-5.698,23.679,-0.316,1.00,47.35,O,None,4lza
5531,HETATM,2852,O,HOH,B,288,-6.332,-13.026,-3.481,1.00,51.79,O,None,4lza
5532,HETATM,2853,O,HOH,B,289,-8.265,-14.563,-0.902,1.00,50.84,O,None,4lza
5533,HETATM,2854,O,HOH,B,290,-28.824,12.440,-1.084,1.00,46.14,O,None,4lza

## This function I wrote only returns atom and hetatm
<a id='42'></a>

In [29]:
def get_atom_and_hetatm(pdb_id):
    """ Return the atom sequence of a pdb file as a pandas dataframe
    
    >>> get_atom_hetatm('4Z0L')
    >>> get_atom_hetatm('4lza')
    """
    pdb_file = get_pdb_file(pdb_id, filetype='pdb', compression=False)
    # using a get_pdb_file() function from pypdb package to return a file with format 'pdb'
    file1 = pdb_file.splitlines()
    list_atom = []
    
    # we only select line with atom and hetatm
    for line in file1:
        if line[:4] == "ATOM" or line[:6] == "HETATM":
            list_atom.append(line)
        
    list_s_atom = [s.split() for s in list_atom]
    # split each string in a list by white spaces
    df = pd.DataFrame(list_s_atom)
    # use DataFrame function to convert a list to dataframe
    df["id"] = pdb_id
    # add one id column to exsiting dataframe
    return(df)

In [30]:
get_atom_and_hetatm("4lza")

,0,1,2,3,4,5,6,7,8,9,10,11,id
0,ATOM,1,N,THR,A,0,-27.785,5.217,-21.426,1.00,50.53,N,4lza
1,ATOM,2,CA,THR,A,0,-27.459,5.049,-19.974,1.00,49.41,C,4lza
2,ATOM,3,C,THR,A,0,-25.949,5.130,-19.667,1.00,46.13,C,4lza
3,ATOM,4,O,THR,A,0,-25.572,5.789,-18.699,1.00,44.22,O,4lza
4,ATOM,5,CB,THR,A,0,-28.153,3.815,-19.346,1.00,51.85,C,4lza
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2847,HETATM,2850,O,HOH,B,286,-0.332,17.645,1.000,1.00,42.23,O,4lza
2848,HETATM,2851,O,HOH,B,287,-5.698,23.679,-0.316,1.00,47.35,O,4lza
2849,HETATM,2852,O,HOH,B,288,-6.332,-13.026,-3.481,1.00,51.79,O,4lza
2850,HETATM,2853,O,HOH,B,289,-8.265,-14.563,-0.902,1.00,50.84,O,4lza
2851,HETATM,2854,O,HOH,B,290,-28.824,12.440,-1.084,1.00,46.14,O,4lza

<a id='43'></a>
# I create a class for each `pdb_id` which can return attribute/desired fields and with methods we want

In [31]:
import warnings

In [453]:
class pdb:
    """A class of each pdb_id file, including desired attributes and methods"""
    
    def __init__(self, pdb_id):
        """Create a object given a specific id"""
        
        self.id = pdb_id
        self.file = get_pdb_file(pdb_id, filetype='pdb', compression=False)
        if self.file == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            self.list = None
        else:
            self.list = self.file.splitlines()
        
    def get_enzyme_type(self):
        """get the enzyme type of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if line[:6] == "HEADER":
                lis = line.split()[1:]
                res = ""
                for i in lis:
                    if not re.findall("^[0-3][1-9]-[A-Z]{3,}-[0-9][0-9]$", i):
                        res = res + i + " "
                    else:
                        break
                return(res.rstrip())
        warnings.warn("This pdb file doesn't have enzyme type.")
            
    def get_name(self):
        """get molecue name of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if "MOLECULE:" in line:
                res = line[line.find("MOLECULE:")+10:]
                if ";" in res:
                    return(res[:res.find(";")])
                else:
                    res = res.rstrip() + self.list[self.list.index(line)+1][11:]
                    return(res[:res.find(";")])
        warnings.warn("This pdb file doesn't have name field.")
            
    def get_organism_name(self):
        """get organism name of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if "ORGANISM_SCIENTIFIC:" in line:
                res = line[line.find("ORGANISM_SCIENTIFIC:")+21:]
                return(res[:res.find(";")])
        warnings.warn("This pdb file doesn't have organism name field.")
            
    def get_organism_taxid(self):
        """get organism taxid of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if "ORGANISM_TAXID:" in line:
                res = line[line.find("ORGANISM_TAXID:")+16:]
                return(res[:res.find(";")])
        warnings.warn("This pdb file doesn't have organism tax id field.")
            
    def get_chain_id(self):
        """get chain id of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        chain_id = ""
        for line in self.list:
            if "CHAIN:" in line:
                res = line[line.find("CHAIN:")+7:]
                chain_id += res[:res.find(";")] + ", "
        if chain_id:
            return chain_id.rstrip(", ")
        warnings.warn("This pdb file doesn't have chain id field.")
            
    
    def get_ec_number(self):
        """get EC number of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if "EC:" in line:
                res = line[line.find("EC:")+4:]
                return(res[:res.find(";")])
        warnings.warn("This pdb file doesn't have EC number field.")
            
    def get_strain(self):
        """get strain of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if "STRAIN:" in line:
                res = line[line.find("STRAIN:")+8:]
                return(res[:res.find(";")])
        warnings.warn("This pdb file doesn't have this strain field.")
    
    def get_gene(self):
        """get gene of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if "GENE:" in line:
                res = line[line.find("GENE:")+6:]
                return(res[:res.find(";")])
        warnings.warn("This pdb file doesn't have this gene field.")
            
    def get_resolution(self):
        """get resolution of this pdb"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        for line in self.list:
            if "RESOLUTION." in line and "ANGSTROMS." in line:
                num = line.find("RESOLUTION.") + 11
                while line[num] == " ":
                    num = num + 1
                    if line[num] != " ":
                        res = line[num:]
                        break
                return(res[:res.find("ANGSTROMS.")+9])
        warnings.warn("This pdb file doesn't have this resolution field.")
            
    def get_seqres(self):
        """get the seqres sequence of a pdb file"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        list_se = []
        for line in self.list:
            if line[:6] == "SEQRES":
                list_se.append(line)
        if list_se == []:
            warnings.warn("This pdb file doesn't have Seqres sequence field.")
            return(None)
        list_se = [s.split() for s in list_se]
        df = pd.DataFrame(list_se)
        return(df)
    
    def get_atom_and_hetatm(self):
        """get the atom and hetatm sequence of a pdb file as a pandas dataframe"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        list_atom = []
        # we only select line with atom and hetatm
        for line in self.list:
            if line[:4] == "ATOM" or line[:6] == "HETATM":
                list_atom.append(line)
        
        if list_atom == []:
            warnings.warn("This pdb file doesn't have atom and hetatm field.")
            return None
        list_s_atom = []
        # according to the string position to make a list of each row
        for line in list_atom:
            l = []
            if line[:6].isspace():
                l.append(None)
            else:
                l.append(line[:6].split()[0])
            if line[6:11].isspace():
                l.append(None)
            else:
                l.append(line[6:11].split()[0])
            
            if line[12:16].isspace():
                l.append(None)
            else:
                l.append(line[12:16].split()[0])
                
            if line[16].isspace():
                l.append(None)
            else:
                l.append(line[16].split()[0])
            
            if line[17:20].isspace():
                l.append(None)
            else:
                l.append(line[17:20].split()[0])
                
            if line[21].isspace():
                l.append(None)
            else:
                l.append(line[21].split()[0])
                
            if line[22:26].isspace():
                l.append(None)
            else:
                l.append(line[22:26].split()[0])
                
            if line[26].isspace():
                l.append(None)
            else:
                l.append(line[26].split()[0])
                
            if line[30:38].isspace():
                l.append(None)
            else:
                l.append(line[30:38].split()[0])
                
            if line[38:46].isspace():
                l.append(None)
            else:
                l.append(line[38:46].split()[0])
                
            if line[46:54].isspace():
                l.append(None)
            else:
                l.append(line[46:54].split()[0])
                
            if line[54:60].isspace():
                l.append(None)
            else:
                l.append(line[54:60].split()[0])
                
            if line[60:66].isspace():
                l.append(None)
            else:
                l.append(line[60:66].split()[0])
                
            if line[76:78].isspace():
                l.append(None)
            else:
                l.append(line[76:78].split()[0])
                
            if line[78:80].isspace():
                l.append(None)
            else:
                l.append(line[78:80].split()[0])
            
            list_s_atom.append(l)
                
        df = pd.DataFrame(list_s_atom)
        # use DataFrame function to convert a list to dataframe
        df.columns = ["Record Name", "serial", "name", "altLoc", "resName", "chainID", "resSeq", 
                     "iCode", "x", "y", "z", "occupancy", "tempFactor", "element", "charge"]
        return(df)
    
    def get_missing_residue(self):
        """get the missing residue as a pandas data frame"""
        
        if self.list == None:
            warnings.warn("This pdb id file doesn't have a pdb format file")
            return None
        
        res = None
        
        for line in self.list:
            if "MISSING RESIDUES" in line:
                res = line
        
        if res == None:
            warnings.warn("This pdb file doesn't have Missing Residue field.")
            return None
        
        inx = self.list.index(res)
        
        while True:
            if ("M RES C SSSEQI" not in self.list[inx]) and ("RES C SSSEQI" not in self.list[inx]):
                inx = inx + 1
            else:
                break
        
        if "M RES C SSSEQI" in self.list[inx]:
            flag = 1
        elif "RES C SSSEQI" in self.list[inx]:
            flag = 0
            
        inx += 1
        
        list_miss = []
        if flag:
        # according to the string position to make a list of each row
            while not self.list[inx][10:].isspace():
                l = []
                line = self.list[inx]
                if line[13].isspace():
                    l.append(None)
                else:
                    l.append(line[13])
                if line[15:18].isspace():
                    l.append(None)
                else:
                    l.append(line[15:18])
                if line[19].isspace():
                    l.append(None)
                else:
                    l.append(line[19])
                if line[21:26].isspace():
                    l.append(None)
                else:
                    l.append(line[21:26])
                if line[26].isspace():
                    l.append(None)
                else:
                    l.append(line[26])
                list_miss.append(l)
                inx = inx + 1
        else:
            while not self.list[inx][10:].isspace():
                l = []
                line = self.list[inx]

                if line[15:18].isspace():
                    l.append(None)
                else:
                    l.append(line[15:18])
                if line[19].isspace():
                    l.append(None)
                else:
                    l.append(line[19])
                if line[21:26].isspace():
                    l.append(None)
                else:
                    l.append(line[21:26])
                if line[26].isspace():
                    l.append(None)
                else:
                    l.append(line[26])
                list_miss.append(l)
                inx = inx + 1
        
        df = pd.DataFrame(list_miss)
        if flag:
            df.columns = ["MODEL NUMBER", "RESIDUE NAME", "CHAIN IDENTIFIER", "SEQUENCE NUMBER", "INSERTION CODE"]
        else:
            df.columns = ["RESIDUE NAME", "CHAIN IDENTIFIER", "SEQUENCE NUMBER", "INSERTION CODE"]
        return(df)

<a id=44></a>
### an example of 4lza object of this class

In [454]:
_4lza = pdb("4lza")
print(_4lza.id)

4lza

In [455]:
print(_4lza.list[:2])

['HEADER    TRANSFERASE                             31-JUL-13   4LZA              ', 'TITLE     CRYSTAL STRUCTURE OF ADENINE PHOSPHORIBOSYLTRANSFERASE FROM           ']

In [456]:
print(_4lza.get_enzyme_type())

TRANSFERASE

In [431]:
print(_4lza.get_name())

ADENINE PHOSPHORIBOSYLTRANSFERASE

In [432]:
print(_4lza.get_organism_name())

THERMOANAEROBACTER PSEUDETHANOLICUS

In [433]:
print(_4lza.get_organism_taxid())

340099

In [434]:
print(_4lza.get_chain_id())

A, B

In [435]:
print(_4lza.get_ec_number())

2.4.2.7

In [436]:
print(_4lza.get_strain())

ATCC 33223

In [437]:
print(_4lza.get_gene())

166856274, APT, TETH39_1027

In [438]:
print(_4lza.get_resolution())

1.84 ANGSTROMS

In [439]:
_4lza.get_seqres()[:10]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,SEQRES,1,A,195,MSE,HIS,HIS,HIS,HIS,HIS,HIS,SER,SER,GLY,VAL,ASP,LEU
1,SEQRES,2,A,195,GLY,THR,GLU,ASN,LEU,TYR,PHE,GLN,SER,MSE,THR,LEU,GLU
2,SEQRES,3,A,195,GLU,ILE,LYS,MSE,MSE,ILE,ARG,GLU,ILE,PRO,ASP,PHE,PRO
3,SEQRES,4,A,195,LYS,LYS,GLY,ILE,LYS,PHE,LYS,ASP,ILE,THR,PRO,VAL,LEU
4,SEQRES,5,A,195,LYS,ASP,ALA,LYS,ALA,PHE,ASN,TYR,SER,ILE,GLU,MSE,LEU
5,SEQRES,6,A,195,ALA,LYS,ALA,LEU,GLU,GLY,ARG,LYS,PHE,ASP,LEU,ILE,ALA
6,SEQRES,7,A,195,ALA,PRO,GLU,ALA,ARG,GLY,PHE,LEU,PHE,GLY,ALA,PRO,LEU
7,SEQRES,8,A,195,ALA,TYR,ARG,LEU,GLY,VAL,GLY,PHE,VAL,PRO,VAL,ARG,LYS
8,SEQRES,9,A,195,PRO,GLY,LYS,LEU,PRO,ALA,GLU,THR,LEU,SER,TYR,GLU,TYR
9,SEQRES,10,A,195,GLU,LEU,GLU,TYR,GLY,THR,ASP,SER,LEU,GLU,ILE,HIS,LYS

In [440]:
_4lza.get_atom_and_hetatm().head(5)

,Record Name,serial,name,altLoc,resName,chainID,resSeq,iCode,x,y,z,occupancy,tempFactor,element,charge
0,ATOM,1,N,None,THR,A,0,None,-27.785,5.217,-21.426,1.00,50.53,N,None
1,ATOM,2,CA,None,THR,A,0,None,-27.459,5.049,-19.974,1.00,49.41,C,None
2,ATOM,3,C,None,THR,A,0,None,-25.949,5.130,-19.667,1.00,46.13,C,None
3,ATOM,4,O,None,THR,A,0,None,-25.572,5.789,-18.699,1.00,44.22,O,None
4,ATOM,5,CB,None,THR,A,0,None,-28.153,3.815,-19.346,1.00,51.85,C,None

In [441]:
_4lza.get_missing_residue()[:10]

  MODEL NUMBER RESIDUE NAME CHAIN IDENTIFIER SEQUENCE NUMBER INSERTION CODE
0         None          MSE                A             -23           None
1         None          HIS                A             -22           None
2         None          HIS                A             -21           None
3         None          HIS                A             -20           None
4         None          HIS                A             -19           None
5         None          HIS                A             -18           None
6         None          HIS                A             -17           None
7         None          SER                A             -16           None
8         None          SER                A             -15           None
9         None          GLY                A             -14           None

<a id=5></a>
# Li Yuan's fifth week work

## We want to create a general table which includes all desired fields except Atom and Hetatm

<a id=51></a>
### I wrote this method outside the above class, but we can add this method later into the class

In [48]:
def get_general_table(self):
    """get a general table of this pdb file"""
    
    if self.list == None:
        warnings.warn("This pdb id file doesn't have a pdb format file")
        return(pd.DataFrame({"PDB_ID": [self.id],
                       "Enzyme_Type": [None],
                       "Name": [None],
                       "Organism_Name": [None],
                       "Organism_Taxid": [None],
                       "Ec_Number": [None],
                       "Strain": [None],
                       "Gene": [None],
                       "Resolution": [None],
                       "Chain_Id": [None],
                       "Num_Seqres": [None],
                       "Seqres": [None],
                       "Num_Missing": [None],
                       "Missing_Residue": [None],
                       "Missing_Id": [None]
                       }))
    
    chain_id = self.get_chain_id().split(", ")
    num_chain = len(chain_id)
    
    PDB_ID = [self.id] * num_chain
    Enzyme_Type = [self.get_enzyme_type()] * num_chain
    Name = [self.get_name()] * num_chain
    Organism_Name = [self.get_organism_name()] * num_chain
    Organism_Taxid = [self.get_organism_taxid()] * num_chain
    Ec_Number = [self.get_ec_number()] * num_chain
    Strain = [self.get_strain()] * num_chain
    Gene = [self.get_gene()] * num_chain
    Resolution = [self.get_resolution()] * num_chain
    Seqres = self.get_seqres()
    
    Num_Seqres = []
    Seqres_total = []
    for iid in chain_id:
        se = Seqres[Seqres[2] == iid].loc[:, 4:].values.tolist()
        a = []
        [a.extend(i) for i in se]
        Num_Seqres.append(len(a))
        Seqres_total.append(a)
    
    Num_Missing = []
    Missing = self.get_missing_residue()
    Missing_Residue = []
    Missing_Id = []
    
    if isinstance(Missing, str) or Missing is None:
        Num_Missing = [None] * num_chain
        Missing_Residue = [None] * num_chain
        Missing_Id = [None] * num_chain
    else:
        for iid in chain_id:
            se = Missing[Missing["CHAIN IDENTIFIER"] == iid]
            a = se["RESIDUE NAME"].values.tolist()
            b = se["SEQUENCE NUMBER"].values.tolist()
            Num_Missing.append(len(a))
            Missing_Residue.append(a)
            Missing_Id.append(b)
    
    df = pd.DataFrame({"PDB_ID": PDB_ID,
                       "Enzyme_Type": Enzyme_Type,
                       "Name": Name,
                       "Organism_Name": Organism_Name,
                       "Organism_Taxid": Organism_Taxid,
                       "Ec_Number": Ec_Number,
                       "Strain": Strain,
                       "Gene": Gene,
                       "Resolution": Resolution,
                       "Chain_Id": chain_id,
                       "Num_Seqres": Num_Seqres,
                       "Seqres": Seqres_total,
                       "Num_Missing": Num_Missing,
                       "Missing_Residue": Missing_Residue,
                       "Missing_Id": Missing_Id
                       })
    return(df)

## Now we add above function as a method of the class we defind in the previous week.

In [49]:
pdb.get_general_table = get_general_table

## Now we test this method to generate this general table in a form of Pandas DataFrame.

In [147]:
_4lza.get_general_table()

,PDB_ID,Enzyme_Type,Name,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,4lza,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",1.84 ANGSTROMS,A,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",27,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -..."
1,4lza,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",1.84 ANGSTROMS,B,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",23,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -..."

<a id=52></a>
## Now we want to create a table which only includes Atom and Hetatm.

In [457]:
def get_atom_hetatm_table(self):
    """get a table which only includes atom and hetatm"""
    
    if self.list == None:
        warnings.warn("This pdb id file doesn't have a pdb format file")
        return(pd.DataFrame({'Record Name':[None], 'name':[None], 'Name':[None], 'serial':[None], 'altLoc':[None], 'resName':[None], 'chainID':[None], 'resSeq':[None],
       'iCode':[None], 'x':[None], 'y':[None], 'z':[None], 'occupancy':[None], 'tempFactor':[None], 'element':[None], 'charge':[None],
       'PDB ID':[self.id], 'Atomic Number':[None], 'Atomic Weight':[None]}))
        
    table = self.get_atom_and_hetatm()
    if not isinstance(table, pd.DataFrame):
        return(pd.DataFrame({'Record Name':[None], 'name':[None], 'Name':[None], 'serial':[None], 'altLoc':[None], 'resName':[None], 'chainID':[None], 'resSeq':[None],
       'iCode':[None], 'x':[None], 'y':[None], 'z':[None], 'occupancy':[None], 'tempFactor':[None], 'element':[None], 'charge':[None],
       'PDB ID':[self.id], 'Atomic Number':[None], 'Atomic Weight':[None]}))
    table["PDB ID"] = self.id
    
    atom_table = pd.read_csv("/Users/liyuan/Documents/Chemistry_research/week5/atom.csv")
    atom_table["Symbol"] = atom_table["Symbol"].str.upper()
    
    #df = table.set_index("name").join(atom_table.set_index("Symbol"), how="left")[['Record Name', 'Name', 'serial', 'altLoc', 'resName', 'chainID', 'resSeq',
    #   'iCode', 'x', 'y', 'z', 'occupancy', 'tempFactor', 'element', 'charge',
    #   'PDB ID', 'Atomic Number', 'Atomic Weight']]
    df = pd.merge(table, atom_table, how = "left", left_on = "name", right_on = "Symbol")[['Record Name', 'name', 'Name', 'serial', 'altLoc', 'resName', 'chainID', 'resSeq',
       'iCode', 'x', 'y', 'z', 'occupancy', 'tempFactor', 'element', 'charge',
       'PDB ID', 'Atomic Number', 'Atomic Weight']]
    
    return(df)

pdb.get_atom_hetatm_table = get_atom_hetatm_table

_4lza.get_atom_hetatm_table()

,Record Name,name,Name,serial,altLoc,resName,chainID,resSeq,iCode,x,y,z,occupancy,tempFactor,element,charge,PDB ID,Atomic Number,Atomic Weight
0,ATOM,N,Nitrogen,1,None,THR,A,0,None,-27.785,5.217,-21.426,1.00,50.53,N,None,4lza,7.0,14.0067
1,ATOM,CA,Calcium,2,None,THR,A,0,None,-27.459,5.049,-19.974,1.00,49.41,C,None,4lza,20.0,40.08
2,ATOM,C,Carbon,3,None,THR,A,0,None,-25.949,5.130,-19.667,1.00,46.13,C,None,4lza,6.0,12.011
3,ATOM,O,Oxygen,4,None,THR,A,0,None,-25.572,5.789,-18.699,1.00,44.22,O,None,4lza,8.0,15.9994
4,ATOM,CB,NaN,5,None,THR,A,0,None,-28.153,3.815,-19.346,1.00,51.85,C,None,4lza,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2847,HETATM,O,Oxygen,2850,None,HOH,B,286,None,-0.332,17.645,1.000,1.00,42.23,O,None,4lza,8.0,15.9994
2848,HETATM,O,Oxygen,2851,None,HOH,B,287,None,-5.698,23.679,-0.316,1.00,47.35,O,None,4lza,8.0,15.9994
2849,HETATM,O,Oxygen,2852,None,HOH,B,288,None,-6.332,-13.026,-3.481,1.00,51.79,O,None,4lza,8.0,15.9994
2850,HETATM,O,Oxygen,2853,None,HOH,B,289,None,-8.265,-14.563,-0.902,1.00,50.84,O,None,4lza,8.0,15.9994
2851,HETATM,O,Oxygen,2854,None,HOH,B,290,None,-28.824,12.440,-1.084,1.00,46.14,O,None,4lza,8.0,15.9994

## This is the atomic table I use to merge with atom and hetatm table

In [52]:
pd.read_csv("/Users/liyuan/Documents/Chemistry_research/week5/atom.csv").set_index("Symbol")

        Atomic Number        Name Atomic Weight
Symbol
H                   1    Hydrogen       1.00797
He                  2      Helium       4.00260
Li                  3     Lithium         6.941
Be                  4   Beryllium       9.01218
B                   5       Boron         10.81
...               ...         ...           ...
Db                105     Dubnium         (262)
Sg                106  Seaborgium         (263)
Uun               110  Ununnilium         (269)
Uuu               111   Unununium         (272)
Uub               112   Ununbiium         (277)

[112 rows x 3 columns]

## Because all the packages which can import element periodic table are unable to install on my current python version 3.8 which is too high and can't be compatiable with lower version of those packages and I don't want to churn different python version, so I found a mass.py online to be as mass file to use.

## I copy a atom table from a [website](https://www.angelo.edu/faculty/kboudrea/periodic/structure_mass.htm) and paste into Number App on mac then I export this file as a CSV file, last I use read_csv() function to import this table into this python file.

# So when you run this file, make sure to change the file path inside function `get_atom_hetatm_table()` to your own computer's instead of using mine. Thanks.

# Now we test 100 general tables of pdb file

# Legacy Search API Web Service will be shutdown on December 9th, 2020. Queries made to this API endpoints will fail.

get_all()[:11]

<a id=53></a>
## Next we want to compute running time of extracting 100 pdb general tables 
### We use `timeit` package to compute this

import timeit

start = timeit.default_timer()

frames = []
for i in get_all()[:101]:
    df = pdb(i).get_general_table()
    frames.append(df)
    
pd.concat(frames)

stop = timeit.default_timer()

print('Time: ', stop - start)

## We used around 24-35s to extract 100 general tables and merge them into one table

frames = []
for i in get_all()[:101]:
    df = pdb(i).get_general_table()
    frames.append(df)
    
pd.concat(frames)

<a id=54></a>
# Remark: When I ran the first 100 pdb files, I found there was a file called "136D" which only has four columns in the missing residue part, different from other pdb files which includes five columns in missing residue parts. So I made a change to the function `get_missing_residue()` to commodate this difference.

In [613]:
pdb("136D").get_missing_residue()

  RESIDUE NAME CHAIN IDENTIFIER SEQUENCE NUMBER INSERTION CODE
0           DT                A               2              L
1           DT                A               3              L
2           DT                A               4              L
3           DT                A               7              L
4           DT                A               8              L
5           DT                A               9              L

<a id=55></a>
## Now we test the first 100 Atom and Hetatm Table of pdb files and test the time

start = timeit.default_timer()

frames = []
for i in get_all()[:101]:
    df = pdb(i).get_atom_hetatm_table()
    frames.append(df)
    
d = pd.concat(frames)

stop = timeit.default_timer()

print('Time: ', stop - start)

d

## We found we used around 30s to extract 100 atom and htmatm tables and merge them into one longer table.

<a id=56></a>
## Next we test first 100 general table and atom with htmatm tables together and test the overall time

start = timeit.default_timer()

frames = []
for i in get_all()[:101]:
    df = pdb(i).get_atom_hetatm_table()
    frames.append(df)
    
pd.concat(frames)

frames = []
for i in get_all()[:101]:
    df = pdb(i).get_general_table()
    frames.append(df)
    
pd.concat(frames)

stop = timeit.default_timer()

print('Time: ', stop - start)

## We found we used around 60s to extract 100 atom and htmatm tables and general tables then merge them into two longer tables.

<a id=57></a>
# We test the average processing time of 100 random pdb files, and found that average time is around 0.7-1.0

l = len(get_all())
l

time = []
for i in range(20):
    pdb_id = get_all()[random.randint(0, l)]
    start = timeit.default_timer()
    pdb(pdb_id).get_general_table()
    pdb(pdb_id).get_atom_hetatm_table()
    stop = timeit.default_timer()
    time.append(stop - start)
print("Average processing time of one pdb file: ", sum(time) / len(time))

<a id=6></a>
# Li Yuan's sixth - eight week work

## 1.

>One thing I recommend you to do is to randomly sample n PDB IDs at a time, and run the appending code and record time consumed. Then repeat this process for m times. By averaging the running time for m processes, we can get an estimated running time t for running n PDB IDs. After that, we can use the total number of PDB IDs l, to calculate the estimated total running time: (t/n)*l. Although in the real computing process, the running time may be slowing down further when the data size becomes larger, this estimation is still a relatively reasonable method for estimating the total running time. In our case, we want both m and n be large enough to get a good estimation, but also keep in mind that the testing will also take a lot of time when it gets big. So I recommend you to try to use n=100 and m=20 as a starting point, if that doesn’t take so long, you can increase both to try to get a better overall estimation.

n = 100
m = 20

import random

time = []

for _ in range(m):
    randomlist = random.sample(range(0, l+1), n)
    
    start = timeit.default_timer()
    
    frame1 = []; frame2 = []
    
    for i in randomlist:
        df1 = pdb(get_all()[i]).get_atom_hetatm_table()
        df2 = pdb(get_all()[i]).get_general_table()
        frame1.append(df1)
        frame2.append(df2)
    
    pd.concat(frame1)
    pd.concat(frame2)
    
    stop = timeit.default_timer()
    time.append(stop - start)
    
ave = sum(time)/len(time)

ave

(ave / n * l) / (3600 * 24)

<a id=61></a>
## We found that average time of process random 100 pdb files is 248.84s. So from the formula we have in the email you sent me 
$$t = 248.84, n = 100, l = 170383$$ $$\text{Estimated time} = \frac{t}{n}\times l= 4.9 \approx  5 \text{days}$$



## From the error above, we found that there were a couple of pdb files which are None, so `NoneType` object has no attribute `splitlines`. So next we try to search and print all the None pdb files below.

L = get_all()
for i in L:
    if get_pdb_file(i, filetype='pdb', compression=False) == None:
        print(i)

<a id=62></a>
## Because this will take a lot of time to find and print all the `NoneType` files, so I dumb it.

## This means we need to accomondate the error situations in the class we defined above.
### I added `if self.file == None: self.list = None else: self.list = self.file.splitlines()` and `if self.list == None: return None` to the class I defined above to deal with blank pdb files.

## Now we test one of NoneType pdb file

In [612]:
_4U20 = pdb("4U20")
print(_4U20.id)
print(_4U20.file)
print(_4U20.list)

4U20
None
None

../pypdb/pypdb.py:504: UserWarning: Retrieval failed, returning None
  warnings.warn("Retrieval failed, returning None")
<ipython-input-453-da2cafa4f575>:10: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

## After seraching on the RCSB PDB [https://www.rcsb.org/structure/4U20](https://www.rcsb.org/structure/4U20) website, we found that this pdb has corresponding file, but because of large size, we can't access ths PDB format as other files. It only provides PDBx format which is beyond our current class capacity.

## We merge one NoneType pdb file `4U20` with one normal pdb file `4lza`.

In [611]:
df1 = _4U20.get_general_table()
df2 = _4lza.get_general_table()
pd.concat([df1, df2])

<ipython-input-451-f3f537113125>:5: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,...,Chain_Id,Fasta Sequence,Entity ID,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id,Partial Modeled Residue(yellow),Unmodeled Residue(grey)
0,4U20,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,NaN,NaN
0,4LZA,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,No,Homo 2-mer -A2,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",...,A,MHHHHHHSSGVDLGTENLYFQSMTLEEIKMMIREIPDFPKKGIKFK...,1,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",27,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -...",[],"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1,4LZA,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,No,Homo 2-mer -A2,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",...,B,MHHHHHHSSGVDLGTENLYFQSMTLEEIKMMIREIPDFPKKGIKFK...,1,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",23,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -...",[],"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."

In [92]:
df3 = _4U20.get_atom_hetatm_table()
df4 = _4lza.get_atom_hetatm_table()
pd.concat([df3, df4])

<ipython-input-51-bba45be409fd>:5: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

,Record Name,name,Name,serial,altLoc,resName,chainID,resSeq,iCode,x,y,z,occupancy,tempFactor,element,charge,PDB ID,Atomic Number,Atomic Weight
0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,4U20,NaN,None
0,ATOM,N,Nitrogen,1,None,THR,A,0,None,-27.785,5.217,-21.426,1.00,50.53,N,None,4lza,7.0,14.0067
1,ATOM,CA,Calcium,2,None,THR,A,0,None,-27.459,5.049,-19.974,1.00,49.41,C,None,4lza,20.0,40.08
2,ATOM,C,Carbon,3,None,THR,A,0,None,-25.949,5.130,-19.667,1.00,46.13,C,None,4lza,6.0,12.011
3,ATOM,O,Oxygen,4,None,THR,A,0,None,-25.572,5.789,-18.699,1.00,44.22,O,None,4lza,8.0,15.9994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2847,HETATM,O,Oxygen,2850,None,HOH,B,286,None,-0.332,17.645,1.000,1.00,42.23,O,None,4lza,8.0,15.9994
2848,HETATM,O,Oxygen,2851,None,HOH,B,287,None,-5.698,23.679,-0.316,1.00,47.35,O,None,4lza,8.0,15.9994
2849,HETATM,O,Oxygen,2852,None,HOH,B,288,None,-6.332,-13.026,-3.481,1.00,51.79,O,None,4lza,8.0,15.9994
2850,HETATM,O,Oxygen,2853,None,HOH,B,289,None,-8.265,-14.563,-0.902,1.00,50.84,O,None,4lza,8.0,15.9994
2851,HETATM,O,Oxygen,2854,None,HOH,B,290,None,-28.824,12.440,-1.084,1.00,46.14,O,None,4lza,8.0,15.9994

# Li Yuan's seventh week work

## I changed the codes above which calculates the average time of merging 100 general and atam pdb tables. It's around *248.84 s*.  From the formula we have, mergeing all 170k pdb general and atam tables, we need about *5 days* in total.

<a id=63></a>
## Next we added some warning messages to deal with some exceptions in each desired field.

### For example, for `4U20` this id, it doesn't have a pdb format file, so when we create the object of this file, we need to raise a warning to users like below:

### print All the methods of pdb class I defined

In [68]:
dir(pdb)[26:]

['get_atom_and_hetatm',
 'get_atom_hetatm_table',
 'get_chain_id',
 'get_ec_number',
 'get_enzyme_type',
 'get_gene',
 'get_general_table',
 'get_missing_residue',
 'get_name',
 'get_organism_name',
 'get_organism_taxid',
 'get_resolution',
 'get_seqres',
 'get_strain']

In [446]:
pdb("4U20")

<ipython-input-427-da2cafa4f575>:10: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

In [447]:
_4U20 = pdb("4U20")
_4U20.get_enzyme_type()

<ipython-input-427-da2cafa4f575>:10: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")
<ipython-input-427-da2cafa4f575>:19: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

In [448]:
_4U20.get_atom_and_hetatm()

<ipython-input-427-da2cafa4f575>:163: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

## Now we test some pdb files which have pdb format files but miss some desired fields. For example we select `_100D` file.

In [101]:
_100D = pdb("100D")

In [102]:
_100D.get_name()

"DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP*)-R(*G)-3')"

In [119]:
_4lza.get_name()

'ADENINE PHOSPHORIBOSYLTRANSFERASE'

## When we want to retrive some desired fields which are missing, those methods return `None` and raise a warning to indicate that "This pdb file doesn't have this field."

In [449]:
_100D.get_gene()

<ipython-input-33-43be29656e13>:120: UserWarning: This pdb file doesn't have this field.
  warnings.warn("This pdb file doesn't have this field.")

In [450]:
_100D.get_missing_residue()

<ipython-input-33-43be29656e13>:271: UserWarning: This pdb file doesn't have this field.
  warnings.warn("This pdb file doesn't have this field.")

In [66]:
print(_100D.file)

HEADER    DNA-RNA HYBRID                          05-DEC-94   100D
TITLE     CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIMERIC DECAMER
TITLE    2 R(C)D(CGGCGCCG)R(G)-SPERMINE COMPLEX-SPERMINE BINDING TO
TITLE    3 PHOSPHATE ONLY AND MINOR GROOVE TERTIARY BASE-PAIRING
COMPND    MOL_ID: 1;
COMPND   2 MOLECULE: DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP*)-
COMPND   3 R(*G)-3');
COMPND   4 CHAIN: A, B;
COMPND   5 ENGINEERED: YES
SOURCE    MOL_ID: 1;
SOURCE   2 SYNTHETIC: YES
KEYWDS    A-DNA/RNA, DOUBLE HELIX, DNA-RNA HYBRID
EXPDTA    X-RAY DIFFRACTION
AUTHOR    C.BAN,B.RAMAKRISHNAN,M.SUNDARALINGAM
REVDAT   3   24-FEB-09 100D    1       VERSN
REVDAT   2   01-APR-03 100D    1       JRNL
REVDAT   1   31-MAR-95 100D    0
JRNL        AUTH   C.BAN,B.RAMAKRISHNAN,M.SUNDARALINGAM
JRNL        TITL   CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIMERIC
JRNL        TITL 2 DECAMER R(C)D(CGGCGCCG)R(G).SPERMINE
JRNL        TITL 3 COMPLEX--SPERMINE BINDING TO PHOSPHATE ONLY AND
JRNL        TITL 4 MINOR GROOVE TERTIARY BASE-PAIRING.
JRNL        REF    NUCLEIC ACIDS RES.            V.  22  5466 1994
JRNL        REFN                   ISSN 0305-1048
JRNL        PMID   7816639
JRNL        DOI    10.1093/NAR/22.24.5466
REMARK   1
REMARK   2
REMARK   2 RESOLUTION.    1.90 ANGSTROMS.
REMARK   3
REMARK   3 REFINEMENT.
REMARK   3   PROGRAM     : X-PLOR
REMARK   3   AUTHORS     : BRUNGER
REMARK   3
REMARK   3  DATA USED IN REFINEMENT.
REMARK   3   RESOLUTION RANGE HIGH (ANGSTROMS) : 1.90
REMARK   3   RESOLUTION RANGE LOW  (ANGSTROMS) : 8.00
REMARK   3   DATA CUTOFF            (SIGMA(F)) : 1.000
REMARK   3   DATA CUTOFF HIGH         (ABS(F)) : NULL
REMARK   3   DATA CUTOFF LOW          (ABS(F)) : NULL
REMARK   3   COMPLETENESS (WORKING+TEST)   (%) : NULL
REMARK   3   NUMBER OF REFLECTIONS             : 2314
REMARK   3
REMARK   3  FIT TO DATA USED IN REFINEMENT.
REMARK   3   CROSS-VALIDATION METHOD          : NULL
REMARK   3   FREE R VALUE TEST SET SELECTION  : NULL
REMARK   3   R VALUE            (WORKING SET) : 0.145
REMARK   3   FREE R VALUE                     : NULL
REMARK   3   FREE R VALUE TEST SET SIZE   (%) : NULL
REMARK   3   FREE R VALUE TEST SET COUNT      : NULL
REMARK   3   ESTIMATED ERROR OF FREE R VALUE  : NULL
REMARK   3
REMARK   3  FIT IN THE HIGHEST RESOLUTION BIN.
REMARK   3   TOTAL NUMBER OF BINS USED           : NULL
REMARK   3   BIN RESOLUTION RANGE HIGH       (A) : NULL
REMARK   3   BIN RESOLUTION RANGE LOW        (A) : NULL
REMARK   3   BIN COMPLETENESS (WORKING+TEST) (%) : NULL
REMARK   3   REFLECTIONS IN BIN    (WORKING SET) : NULL
REMARK   3   BIN R VALUE           (WORKING SET) : NULL
REMARK   3   BIN FREE R VALUE                    : NULL
REMARK   3   BIN FREE R VALUE TEST SET SIZE  (%) : NULL
REMARK   3   BIN FREE R VALUE TEST SET COUNT     : NULL
REMARK   3   ESTIMATED ERROR OF BIN FREE R VALUE : NULL
REMARK   3
REMARK   3  NUMBER OF NON-HYDROGEN ATOMS USED IN REFINEMENT.
REMARK   3   PROTEIN ATOMS            : 0
REMARK   3   NUCLEIC ACID ATOMS       : 408
REMARK   3   HETEROGEN ATOMS          : 14
REMARK   3   SOLVENT ATOMS            : 67
REMARK   3
REMARK   3  B VALUES.
REMARK   3   FROM WILSON PLOT           (A**2) : NULL
REMARK   3   MEAN B VALUE      (OVERALL, A**2) : NULL
REMARK   3   OVERALL ANISOTROPIC B VALUE.
REMARK   3    B11 (A**2) : NULL
REMARK   3    B22 (A**2) : NULL
REMARK   3    B33 (A**2) : NULL
REMARK   3    B12 (A**2) : NULL
REMARK   3    B13 (A**2) : NULL
REMARK   3    B23 (A**2) : NULL
REMARK   3
REMARK   3  ESTIMATED COORDINATE ERROR.
REMARK   3   ESD FROM LUZZATI PLOT        (A) : NULL
REMARK   3   ESD FROM SIGMAA              (A) : NULL
REMARK   3   LOW RESOLUTION CUTOFF        (A) : NULL
REMARK   3
REMARK   3  CROSS-VALIDATED ESTIMATED COORDINATE ERROR.
REMARK   3   ESD FROM C-V LUZZATI PLOT    (A) : NULL
REMARK   3   ESD FROM C-V SIGMAA          (A) : NULL
REMARK   3
REMARK   3  RMS DEVIATIONS FROM IDEAL VALUES.
REMARK   3   BOND LENGTHS                 (A) : 0.015
REMARK   3   BOND ANGLES            (DEGREES) : 3.80
REMARK   3   DIHEDRAL ANGLES        (DEGREES) : NULL
REMARK   3   IMPROPER ANGLES        (DEGREES) : NULL
REMARK   3
REMARK   3  ISOTROPIC THERMAL MODEL : NULL
REMARK   3
REMARK   3  ISOTROPIC THERMAL FACTOR RESTRAINTS.    RMS    SIGMA
REMARK   3   MAIN-CHAIN BOND              (A**2) : NULL  ; NULL
REMARK   3   MAIN-CHAIN ANGLE             (A**2) : NULL  ; NULL
REMARK   3   SIDE-CHAIN BOND              (A**2) : NULL  ; NULL
REMARK   3   SIDE-CHAIN ANGLE             (A**2) : NULL  ; NULL
REMARK   3
REMARK   3  NCS MODEL : NULL
REMARK   3
REMARK   3  NCS RESTRAINTS.                         RMS   SIGMA/WEIGHT
REMARK   3   GROUP  1  POSITIONAL            (A) : NULL  ; NULL
REMARK   3   GROUP  1  B-FACTOR           (A**2) : NULL  ; NULL
REMARK   3
REMARK   3  PARAMETER FILE  1  : NULL
REMARK   3  TOPOLOGY FILE  1   : NULL
REMARK   3
REMARK   3  OTHER REFINEMENT REMARKS: NULL
REMARK   4
REMARK   4 100D COMPLIES WITH FORMAT V. 3.15, 01-DEC-08
REMARK 100
REMARK 100 THIS ENTRY HAS BEEN PROCESSED BY BNL.
REMARK 200
REMARK 200 EXPERIMENTAL DETAILS
REMARK 200  EXPERIMENT TYPE                : X-RAY DIFFRACTION
REMARK 200  DATE OF DATA COLLECTION        : NULL
REMARK 200  TEMPERATURE           (KELVIN) : 263.00
REMARK 200  PH                             : 7.00
REMARK 200  NUMBER OF CRYSTALS USED        : NULL
REMARK 200
REMARK 200  SYNCHROTRON              (Y/N) : N
REMARK 200  RADIATION SOURCE               : ROTATING ANODE
REMARK 200  BEAMLINE                       : NULL
REMARK 200  X-RAY GENERATOR MODEL          : MACSCIENCE
REMARK 200  MONOCHROMATIC OR LAUE    (M/L) : NULL
REMARK 200  WAVELENGTH OR RANGE        (A) : NULL
REMARK 200  MONOCHROMATOR                  : NULL
REMARK 200  OPTICS                         : NULL
REMARK 200
REMARK 200  DETECTOR TYPE                  : AREA DETECTOR
REMARK 200  DETECTOR MANUFACTURER          : SIEMENS-NICOLET
REMARK 200  INTENSITY-INTEGRATION SOFTWARE : NULL
REMARK 200  DATA SCALING SOFTWARE          : NULL
REMARK 200
REMARK 200  NUMBER OF UNIQUE REFLECTIONS   : 2365
REMARK 200  RESOLUTION RANGE HIGH      (A) : 1.900
REMARK 200  RESOLUTION RANGE LOW       (A) : NULL
REMARK 200  REJECTION CRITERIA  (SIGMA(I)) : NULL
REMARK 200
REMARK 200 OVERALL.
REMARK 200  COMPLETENESS FOR RANGE     (%) : NULL
REMARK 200  DATA REDUNDANCY                : NULL
REMARK 200  R MERGE                    (I) : NULL
REMARK 200  R SYM                      (I) : NULL
REMARK 200  <I/SIGMA(I)> FOR THE DATA SET  : NULL
REMARK 200
REMARK 200 IN THE HIGHEST RESOLUTION SHELL.
REMARK 200  HIGHEST RESOLUTION SHELL, RANGE HIGH (A) : NULL
REMARK 200  HIGHEST RESOLUTION SHELL, RANGE LOW  (A) : NULL
REMARK 200  COMPLETENESS FOR SHELL     (%) : NULL
REMARK 200  DATA REDUNDANCY IN SHELL       : NULL
REMARK 200  R MERGE FOR SHELL          (I) : NULL
REMARK 200  R SYM FOR SHELL            (I) : NULL
REMARK 200  <I/SIGMA(I)> FOR SHELL         : NULL
REMARK 200
REMARK 200 DIFFRACTION PROTOCOL: NULL
REMARK 200 METHOD USED TO DETERMINE THE STRUCTURE: NULL
REMARK 200 SOFTWARE USED: NULL
REMARK 200 STARTING MODEL: NULL
REMARK 200
REMARK 200 REMARK: NULL
REMARK 280
REMARK 280 CRYSTAL
REMARK 280 SOLVENT CONTENT, VS   (%): NULL
REMARK 280 MATTHEWS COEFFICIENT, VM (ANGSTROMS**3/DA): NULL
REMARK 280
REMARK 280 CRYSTALLIZATION CONDITIONS: PH 7.00, VAPOR DIFFUSION, HANGING
REMARK 280  DROP
REMARK 290
REMARK 290 CRYSTALLOGRAPHIC SYMMETRY
REMARK 290 SYMMETRY OPERATORS FOR SPACE GROUP: P 21 21 21
REMARK 290
REMARK 290      SYMOP   SYMMETRY
REMARK 290     NNNMMM   OPERATOR
REMARK 290       1555   X,Y,Z
REMARK 290       2555   -X+1/2,-Y,Z+1/2
REMARK 290       3555   -X,Y+1/2,-Z+1/2
REMARK 290       4555   X+1/2,-Y+1/2,-Z
REMARK 290
REMARK 290     WHERE NNN -> OPERATOR NUMBER
REMARK 290           MMM -> TRANSLATION VECTOR
REMARK 290
REMARK 290 CRYSTALLOGRAPHIC SYMMETRY TRANSFORMATIONS
REMARK 290 THE FOLLOWING TRANSFORMATIONS OPERATE ON THE ATOM/HETATM
REMARK 290 RECORDS IN THIS ENTRY TO PRODUCE CRYSTALLOGRAPHICALLY
REMARK 290 RELATED MOLECULES.
REMARK 290   SMTRY1   1  1.000000  0.000000  0.000000        0.00000
REMARK 290   SMTRY2   1  0.000000  1.000000  0.000000        0.00000
REMARK 290   SMTRY3   1  0.000000  0.000000  1.000000        0.00000
REMARK 290   SMTRY1   2 -1.000000  0.000000  0.000000       11.99000
REMARK 290   SMTRY2   2  0.000000 -1.000000  0.000000        0.00000
REMARK 290   SMTRY3   2  0.000000  0.000000  1.000000       22.42000
REMARK 290   SMTRY1   3 -1.000000  0.000000  0.000000        0.00000
REMARK 290   SMTRY2   3  0.000000  1.000000  0.000000       20.38500
REMARK 290   SMTRY3   3  0.000000  0.000000 -1.000000       22.42000
REMARK 290   SMTRY1   4  1.000000  0.000000  0.000000       11.99000
REMARK 290   SMTRY2   4  0.000000 -1.000000  0.000000       20.38500
REMARK 290   SMTRY3   4  0.000000  0.000000 -1.000000        0.00000
REMARK 290
REMARK 290 REMARK: NULL
REMARK 300
REMARK 300 BIOMOLECULE: 1
REMARK 300 SEE REMARK 350 FOR THE AUTHOR PROVIDED AND/OR PROGRAM
REMARK 300 GENERATED ASSEMBLY INFORMATION FOR THE STRUCTURE IN
REMARK 300 THIS ENTRY. THE REMARK MAY ALSO PROVIDE INFORMATION ON
REMARK 300 BURIED SURFACE AREA.
REMARK 350
REMARK 350 COORDINATES FOR A COMPLETE MULTIMER REPRESENTING THE KNOWN
REMARK 350 BIOLOGICALLY SIGNIFICANT OLIGOMERIZATION STATE OF THE
REMARK 350 MOLECULE CAN BE GENERATED BY APPLYING BIOMT TRANSFORMATIONS
REMARK 350 GIVEN BELOW.  BOTH NON-CRYSTALLOGRAPHIC AND
REMARK 350 CRYSTALLOGRAPHIC OPERATIONS ARE GIVEN.
REMARK 350
REMARK 350 BIOMOLECULE: 1
REMARK 350 AUTHOR DETERMINED BIOLOGICAL UNIT: DIMERIC
REMARK 350 APPLY THE FOLLOWING TO CHAINS: A, B
REMARK 350   BIOMT1   1  1.000000  0.000000  0.000000        0.00000
REMARK 350   BIOMT2   1  0.000000  1.000000  0.000000        0.00000
REMARK 350   BIOMT3   1  0.000000  0.000000  1.000000        0.00000
REMARK 500
REMARK 500 GEOMETRY AND STEREOCHEMISTRY
REMARK 500 SUBTOPIC: COVALENT BOND LENGTHS
REMARK 500
REMARK 500 THE STEREOCHEMICAL PARAMETERS OF THE FOLLOWING RESIDUES
REMARK 500 HAVE VALUES WHICH DEVIATE FROM EXPECTED VALUES BY MORE
REMARK 500 THAN 6*RMSD (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN
REMARK 500 IDENTIFIER; SSEQ=SEQUENCE NUMBER; I=INSERTION CODE).
REMARK 500
REMARK 500 STANDARD TABLE:
REMARK 500 FORMAT: (10X,I3,1X,2(A3,1X,A1,I4,A1,1X,A4,3X),1X,F6.3)
REMARK 500
REMARK 500 EXPECTED VALUES PROTEIN: ENGH AND HUBER, 1999
REMARK 500 EXPECTED VALUES NUCLEIC ACID: CLOWNEY ET AL 1996
REMARK 500
REMARK 500  M RES CSSEQI ATM1   RES CSSEQI ATM2   DEVIATION
REMARK 500     DC B  12   P      DC B  12   O5'     0.067
REMARK 500     DG B  19   N7     DG B  19   C8     -0.037
REMARK 500
REMARK 500 REMARK: NULL
REMARK 500
REMARK 500 GEOMETRY AND STEREOCHEMISTRY
REMARK 500 SUBTOPIC: COVALENT BOND ANGLES
REMARK 500
REMARK 500 THE STEREOCHEMICAL PARAMETERS OF THE FOLLOWING RESIDUES
REMARK 500 HAVE VALUES WHICH DEVIATE FROM EXPECTED VALUES BY MORE
REMARK 500 THAN 6*RMSD (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN
REMARK 500 IDENTIFIER; SSEQ=SEQUENCE NUMBER; I=INSERTION CODE).
REMARK 500
REMARK 500 STANDARD TABLE:
REMARK 500 FORMAT: (10X,I3,1X,A3,1X,A1,I4,A1,3(1X,A4,2X),12X,F5.1)
REMARK 500
REMARK 500 EXPECTED VALUES PROTEIN: ENGH AND HUBER, 1999
REMARK 500 EXPECTED VALUES NUCLEIC ACID: CLOWNEY ET AL 1996
REMARK 500
REMARK 500  M RES CSSEQI ATM1   ATM2   ATM3
REMARK 500     DC A   2   C4' -  C3' -  C2' ANGL. DEV. =  -4.2 DEGREES
REMARK 500     DC A   2   O4' -  C1' -  N1  ANGL. DEV. =   3.2 DEGREES
REMARK 500     DC A   2   N1  -  C2  -  O2  ANGL. DEV. =   4.0 DEGREES
REMARK 500     DC A   2   O3' -  P   -  O5' ANGL. DEV. =  17.0 DEGREES
REMARK 500     DG A   3   C4' -  C3' -  C2' ANGL. DEV. =  -5.0 DEGREES
REMARK 500     DG A   3   O4' -  C1' -  N9  ANGL. DEV. =   6.9 DEGREES
REMARK 500     DG A   3   O3' -  P   -  O5' ANGL. DEV. =  25.6 DEGREES
REMARK 500     DC A   5   O4' -  C1' -  N1  ANGL. DEV. =   2.2 DEGREES
REMARK 500     DC A   5   O3' -  P   -  O5' ANGL. DEV. =  26.2 DEGREES
REMARK 500     DC A   5   O3' -  P   -  OP1 ANGL. DEV. = -16.4 DEGREES
REMARK 500     DG A   6   C4' -  C3' -  C2' ANGL. DEV. =  -5.1 DEGREES
REMARK 500     DG A   6   O3' -  P   -  OP2 ANGL. DEV. =   7.7 DEGREES
REMARK 500     DC A   7   O4' -  C1' -  N1  ANGL. DEV. =   6.8 DEGREES
REMARK 500     DC A   8   C4' -  C3' -  C2' ANGL. DEV. =  -7.1 DEGREES
REMARK 500     DC A   8   O4' -  C1' -  N1  ANGL. DEV. =   2.5 DEGREES
REMARK 500     DG A   9   O4' -  C4' -  C3' ANGL. DEV. =  -2.4 DEGREES
REMARK 500     DG A   9   C4' -  C3' -  C2' ANGL. DEV. =  -6.5 DEGREES
REMARK 500     DG A   9   O4' -  C1' -  C2' ANGL. DEV. =  -6.5 DEGREES
REMARK 500     DG A   9   O4' -  C1' -  N9  ANGL. DEV. =   5.6 DEGREES
REMARK 500     DG A   9   C8  -  N9  -  C4  ANGL. DEV. =  -3.0 DEGREES
REMARK 500     DG A   9   O3' -  P   -  OP2 ANGL. DEV. =  12.7 DEGREES
REMARK 500     DG A   9   O3' -  P   -  OP1 ANGL. DEV. = -13.4 DEGREES
REMARK 500      G A  10   O3' -  P   -  O5' ANGL. DEV. = -18.5 DEGREES
REMARK 500      G A  10   O3' -  P   -  OP2 ANGL. DEV. =  28.4 DEGREES
REMARK 500      G A  10   O3' -  P   -  OP1 ANGL. DEV. = -16.5 DEGREES
REMARK 500     DC B  12   O4' -  C1' -  N1  ANGL. DEV. =   4.5 DEGREES
REMARK 500     DC B  12   N1  -  C2  -  O2  ANGL. DEV. =   4.4 DEGREES
REMARK 500     DC B  12   O3' -  P   -  OP2 ANGL. DEV. =  23.0 DEGREES
REMARK 500     DC B  12   O3' -  P   -  OP1 ANGL. DEV. = -20.1 DEGREES
REMARK 500     DG B  13   O4' -  C1' -  N9  ANGL. DEV. =   2.0 DEGREES
REMARK 500     DG B  13   O3' -  P   -  O5' ANGL. DEV. =  17.9 DEGREES
REMARK 500     DG B  14   C4' -  C3' -  C2' ANGL. DEV. =  -4.7 DEGREES
REMARK 500     DG B  14   O3' -  P   -  OP2 ANGL. DEV. =   6.8 DEGREES
REMARK 500     DC B  15   O4' -  C1' -  N1  ANGL. DEV. =   4.3 DEGREES
REMARK 500     DC B  15   N1  -  C2  -  O2  ANGL. DEV. =   4.0 DEGREES
REMARK 500     DC B  15   O3' -  P   -  OP2 ANGL. DEV. =  10.3 DEGREES
REMARK 500     DG B  16   C4' -  C3' -  C2' ANGL. DEV. =  -8.0 DEGREES
REMARK 500     DC B  15   C3' -  O3' -  P   ANGL. DEV. =  -8.8 DEGREES
REMARK 500     DG B  16   O3' -  P   -  O5' ANGL. DEV. =  31.4 DEGREES
REMARK 500     DG B  16   O3' -  P   -  OP1 ANGL. DEV. = -18.4 DEGREES
REMARK 500     DC B  17   O4' -  C1' -  N1  ANGL. DEV. =   4.8 DEGREES
REMARK 500     DC B  17   O3' -  P   -  OP1 ANGL. DEV. = -23.7 DEGREES
REMARK 500     DC B  18   N1  -  C2  -  O2  ANGL. DEV. =   4.5 DEGREES
REMARK 500     DC B  18   O3' -  P   -  OP2 ANGL. DEV. =  12.0 DEGREES
REMARK 500     DG B  19   O4' -  C4' -  C3' ANGL. DEV. =  -2.5 DEGREES
REMARK 500     DG B  19   O3' -  P   -  OP1 ANGL. DEV. = -18.5 DEGREES
REMARK 500
REMARK 500 REMARK: NULL
REMARK 500
REMARK 500 GEOMETRY AND STEREOCHEMISTRY
REMARK 500 SUBTOPIC: PLANAR GROUPS
REMARK 500
REMARK 500 PLANAR GROUPS IN THE FOLLOWING RESIDUES HAVE A TOTAL
REMARK 500 RMS DISTANCE OF ALL ATOMS FROM THE BEST-FIT PLANE
REMARK 500 BY MORE THAN AN EXPECTED VALUE OF 6*RMSD, WITH AN
REMARK 500 RMSD 0.02 ANGSTROMS, OR AT LEAST ONE ATOM HAS
REMARK 500 AN RMSD GREATER THAN THIS VALUE
REMARK 500 (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN IDENTIFIER;
REMARK 500 SSEQ=SEQUENCE NUMBER; I=INSERTION CODE).
REMARK 500
REMARK 500  M RES CSSEQI        RMS     TYPE
REMARK 500      C A   1         0.07    SIDE_CHAIN
REMARK 500     DG A   3         0.10    SIDE_CHAIN
REMARK 500     DG A   4         0.08    SIDE_CHAIN
REMARK 500     DG A   6         0.07    SIDE_CHAIN
REMARK 500      C B  11         0.07    SIDE_CHAIN
REMARK 500     DG B  14         0.09    SIDE_CHAIN
REMARK 500     DC B  15         0.08    SIDE_CHAIN
REMARK 500
REMARK 500 REMARK: NULL
REMARK 525
REMARK 525 SOLVENT
REMARK 525
REMARK 525 THE SOLVENT MOLECULES HAVE CHAIN IDENTIFIERS THAT
REMARK 525 INDICATE THE POLYMER CHAIN WITH WHICH THEY ARE MOST
REMARK 525 CLOSELY ASSOCIATED. THE REMARK LISTS ALL THE SOLVENT
REMARK 525 MOLECULES WHICH ARE MORE THAN 5A AWAY FROM THE
REMARK 525 NEAREST POLYMER CHAIN (M = MODEL NUMBER;
REMARK 525 RES=RESIDUE NAME; C=CHAIN IDENTIFIER; SSEQ=SEQUENCE
REMARK 525 NUMBER; I=INSERTION CODE):
REMARK 525
REMARK 525  M RES CSSEQI
REMARK 525    HOH A  73        DISTANCE =  7.13 ANGSTROMS
REMARK 800
REMARK 800 SITE
REMARK 800 SITE_IDENTIFIER: AC1
REMARK 800 EVIDENCE_CODE: SOFTWARE
REMARK 800 SITE_DESCRIPTION: BINDING SITE FOR RESIDUE SPM A 21
DBREF  100D A    1    10  PDB    100D     100D             1     10
DBREF  100D B   11    20  PDB    100D     100D            11     20
SEQRES   1 A   10    C  DC  DG  DG  DC  DG  DC  DC  DG   G
SEQRES   1 B   10    C  DC  DG  DG  DC  DG  DC  DC  DG   G
HET    SPM  A  21      14
HETNAM     SPM SPERMINE
FORMUL   3  SPM    C10 H26 N4
FORMUL   4  HOH   *67(H2 O)
SITE     1 AC1 13  DC A   5   DG A   6   DG A   9  HOH A  29
SITE     2 AC1 13 HOH A  46  HOH A  56  HOH A  87   DG B  13
SITE     3 AC1 13  DG B  14   DG B  19    G B  20  HOH B  33
SITE     4 AC1 13 HOH B  52
CRYST1   23.980   40.770   44.840  90.00  90.00  90.00 P 21 21 21    8
ORIGX1      1.000000  0.000000  0.000000        0.00000
ORIGX2      0.000000  1.000000  0.000000        0.00000
ORIGX3      0.000000  0.000000  1.000000        0.00000
SCALE1      0.041701  0.000000  0.000000        0.00000
SCALE2      0.000000  0.024528  0.000000        0.00000
SCALE3      0.000000  0.000000  0.022302        0.00000
ATOM      1  O5'   C A   1      -4.549   5.095   4.262  1.00 28.71           O
ATOM      2  C5'   C A   1      -4.176   6.323   3.646  1.00 27.35           C
ATOM      3  C4'   C A   1      -3.853   7.410   4.672  1.00 24.41           C
ATOM      4  O4'   C A   1      -4.992   7.650   5.512  1.00 22.53           O
ATOM      5  C3'   C A   1      -2.713   7.010   5.605  1.00 23.56           C
ATOM      6  O3'   C A   1      -1.379   7.127   5.060  1.00 21.02           O
ATOM      7  C2'   C A   1      -2.950   7.949   6.756  1.00 23.73           C
ATOM      8  O2'   C A   1      -2.407   9.267   6.554  1.00 23.93           O
ATOM      9  C1'   C A   1      -4.489   7.917   6.825  1.00 20.60           C
ATOM     10  N1    C A   1      -4.931   6.902   7.826  1.00 19.25           N
ATOM     11  C2    C A   1      -4.838   7.263   9.158  1.00 16.72           C
ATOM     12  O2    C A   1      -4.287   8.308   9.505  1.00 15.49           O
ATOM     13  N3    C A   1      -5.367   6.448  10.085  1.00 15.96           N
ATOM     14  C4    C A   1      -5.978   5.310   9.736  1.00 16.84           C
ATOM     15  N4    C A   1      -6.592   4.588  10.676  1.00 19.14           N
ATOM     16  C5    C A   1      -6.059   4.907   8.376  1.00 17.68           C
ATOM     17  C6    C A   1      -5.522   5.732   7.461  1.00 17.68           C
ATOM     18  P    DC A   2      -0.178   6.220   5.647  1.00 24.85           P
ATOM     19  OP1  DC A   2       0.915   6.451   4.671  1.00 25.96           O
ATOM     20  OP2  DC A   2      -0.948   4.954   5.664  1.00 24.57           O
ATOM     21  O5'  DC A   2       0.435   6.502   7.097  1.00 24.10           O
ATOM     22  C5'  DC A   2       1.020   7.793   7.281  1.00 19.66           C
ATOM     23  C4'  DC A   2       1.034   8.184   8.738  1.00 17.99           C
ATOM     24  O4'  DC A   2      -0.290   8.244   9.222  1.00 17.23           O
ATOM     25  C3'  DC A   2       1.724   7.167   9.617  1.00 18.98           C
ATOM     26  O3'  DC A   2       3.130   7.395   9.564  1.00 18.39           O
ATOM     27  C2'  DC A   2       1.152   7.607  10.934  1.00 17.33           C
ATOM     28  C1'  DC A   2      -0.273   7.853  10.599  1.00 15.44           C
ATOM     29  N1   DC A   2      -1.070   6.635  10.823  1.00 14.48           N
ATOM     30  C2   DC A   2      -1.417   6.355  12.130  1.00 13.03           C
ATOM     31  O2   DC A   2      -1.007   7.022  13.094  1.00 11.15           O
ATOM     32  N3   DC A   2      -2.233   5.297  12.333  1.00 11.95           N
ATOM     33  C4   DC A   2      -2.681   4.542  11.344  1.00 11.37           C
ATOM     34  N4   DC A   2      -3.532   3.569  11.652  1.00 11.93           N
ATOM     35  C5   DC A   2      -2.314   4.796   9.986  1.00 11.95           C

In [67]:
_100D.get_enzyme_type()

'DNA-RNA HYBRID'

# Bonus: we found the name of this molecular should be "DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP*)-R(*G)-3');", but in our extracted field, we only have "DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP*)-         "

# So next we need to write some check processes to correct these error.

<a id = 64></a>
# But I found this is a very hard process, because there are a lot of pdb files and their formats in pdb file are not unified, there is no standard format in these pdb files. So a function or process which can check each entry extracted used by these method are still basied and not accurate. So I suggest we correct and fix bugs when we find them while we use these tables.

<a id='7'></a>
# Li Yuan's winter break first week work

<a id= '71'></a>
## Extract the FASTA sequence of each PDB file

## Use requests Module to grab web pages to get FASTA sequence

In [133]:
import requests
import re

In [117]:
print(requests.get("https://www.rcsb.org/fasta/entry/4LZA/display").text.split("\n")[1])

MHHHHHHSSGVDLGTENLYFQSMTLEEIKMMIREIPDFPKKGIKFKDITPVLKDAKAFNYSIEMLAKALEGRKFDLIAAPEARGFLFGAPLAYRLGVGFVPVRKPGKLPAETLSYEYELEYGTDSLEIHKDAVLEGQRVVIVDDLLATGGTIYASAKLVESLGGIVDSIIFLTELTFLDGRKKLDGYDIISLIKF

In [458]:
def get_fasta(self):
    """get the fasta sequence of each pdb file"""
    
    full_url = "https://www.rcsb.org/fasta/entry/" + self.id + "/display"
    response = http_requests.request_limited(full_url)
    
    if response.status_code == 200:
        pass
    else:
        warnings.warn("Retrieval failed, returning None")
        return None
    
    L = response.text.split("\n")
    i = 0
    res = {}
    while True:
        if "Chain" in L[i]:
            l = L[i].split("|")
            chain = l[1]
            i = i + 1
            res[chain] = L[i]
            i = i + 1
        elif "Chain" not in L[i] or i >= len(L):
            break
    return res

pdb.get_fasta = get_fasta

In [459]:
pdb("3KJ1").get_fasta()

{'Chain A': 'GSDELYRQSLEIISRYLREQATGAKDTKPMGRSGATSRKALETLRRVGDGVQRNHETAFQGMLRKLDIKNEDDVKSLSRVMIHVFSDGVTNWGRIVTLISFGAFVAKHLKTINQESCIEPLAESITDVLVRTKRDWLVKQRGWDGFVEFFHVEDLEGG',
 'Chain B': 'RPEIWAAQELRRIGDEFNAYYR'}

In [460]:
pdb("3KL2").get_fasta()

{'Chains A,B,C,D,E,F,G,H,I,J,K,L': 'MSLTTSKTRKSGVAMTEKLELDPARTAIVLIEYQNEFTSDGGVLHGAVADVMQHTGMLANTVAVVDAARQAGVPIMHAPITFAEGYGELTRHPYGILKGVVDGKAFVKGTWGAAIVDELAPVNGDIVIEGKRGLDTFASTNLDFILRSKGVDTIVLGGFLTNCCVESTMRTGYERGFRVITLTDCVAATSQEEHNNAISYDFPMFSVPMTSADVIAALEGHHHHHH'}

## Next put FASTA sequence into general table we created above

### Update `get_general_table()` to add FASTA column

In [ ]:
def get_general_table(self):
    """get a general table of this pdb file"""
    
    if self.list == None:
        warnings.warn("This pdb id file doesn't have a pdb format file")
        return(pd.DataFrame({"PDB_ID": [self.id],
                       "Enzyme_Type": [None],
                       "Name": [None],
                       "Organism_Name": [None],
                       "Organism_Taxid": [None],
                       "Ec_Number": [None],
                       "Strain": [None],
                       "Gene": [None],
                       "Resolution": [None],
                       "Chain_Id": [None],
                       "Num_Seqres": [None],
                       "Seqres": [None],
                       "Num_Missing": [None],
                       "Missing_Residue": [None],
                       "Missing_Id": [None]
                       }))
    
    chain_id = self.get_chain_id().split(", ")
    num_chain = len(chain_id)
    
    PDB_ID = [self.id] * num_chain
    Enzyme_Type = [self.get_enzyme_type()] * num_chain
    Name = [self.get_name()] * num_chain
    Organism_Name = [self.get_organism_name()] * num_chain
    Organism_Taxid = [self.get_organism_taxid()] * num_chain
    Ec_Number = [self.get_ec_number()] * num_chain
    Strain = [self.get_strain()] * num_chain
    Gene = [self.get_gene()] * num_chain
    Resolution = [self.get_resolution()] * num_chain
    Seqres = self.get_seqres()
    
    Num_Seqres = []
    Seqres_total = []
    for iid in chain_id:
        se = Seqres[Seqres[2] == iid].loc[:, 4:].values.tolist()
        a = []
        [a.extend(i) for i in se]
        Num_Seqres.append(len(a))
        Seqres_total.append(a)
    
    Num_Missing = []
    Missing = self.get_missing_residue()
    Missing_Residue = []
    Missing_Id = []
    
    if isinstance(Missing, str) or Missing is None:
        Num_Missing = [None] * num_chain
        Missing_Residue = [None] * num_chain
        Missing_Id = [None] * num_chain
    else:
        for iid in chain_id:
            se = Missing[Missing["CHAIN IDENTIFIER"] == iid]
            a = se["RESIDUE NAME"].values.tolist()
            b = se["SEQUENCE NUMBER"].values.tolist()
            Num_Missing.append(len(a))
            Missing_Residue.append(a)
            Missing_Id.append(b)
    
    fasta = []
    dic = self.get_fasta()
    for iid in chain_id:
        fasta.extend([v for k,v in dic.items() if iid in k])
        
    df = pd.DataFrame({"PDB_ID": PDB_ID,
                       "Enzyme_Type": Enzyme_Type,
                       "Name": Name,
                       "Organism_Name": Organism_Name,
                       "Organism_Taxid": Organism_Taxid,
                       "Ec_Number": Ec_Number,
                       "Strain": Strain,
                       "Gene": Gene,
                       "Resolution": Resolution,
                       "Chain_Id": chain_id,
                       "Fasta Sequence": fasta,
                       "Num_Seqres": Num_Seqres,
                       "Seqres": Seqres_total,
                       "Num_Missing": Num_Missing,
                       "Missing_Residue": Missing_Residue,
                       "Missing_Id": Missing_Id
                       })
    return(df)
pdb.get_general_table = get_general_table

In [221]:
#pdb("3kl2").get_general_table()
pdb("3kl2").get_chain_id()

'A, B, C, D, E, F, G, H, I, J, K, L'

In [223]:
pdb("3KJ1").get_general_table()

<ipython-input-205-b4fe648fe448>:99: UserWarning: This pdb file doesn't have this field.
  warnings.warn("This pdb file doesn't have this field.")

,PDB_ID,Enzyme_Type,Name,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Fasta Sequence,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,3KJ1,APOPTOSIS,INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION ...,HOMO SAPIENS,9606,None,BL21(DE3)PLYSS,"BCL2L3, MCL-1, MCL1",1.95 ANGSTROMS,A,GSDELYRQSLEIISRYLREQATGAKDTKPMGRSGATSRKALETLRR...,169,"[GLY, SER, ASP, GLU, LEU, TYR, ARG, GLN, SER, ...",6,"[GLY, ASP, LEU, GLU, GLY, GLY]","[ 170, 323, 324, 325, 326, 327]"
1,3KJ1,APOPTOSIS,INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION ...,HOMO SAPIENS,9606,None,BL21(DE3)PLYSS,"BCL2L3, MCL-1, MCL1",1.95 ANGSTROMS,B,RPEIWAAQELRRIGDEFNAYYR,26,"[ARG, PRO, GLU, ILE, TRP, ALA, ALA, GLN, GLU, ...",0,[],[]

<a id='75'></a>
## Extract Mutation field of each pdb file

In [461]:
def get_mutation(self):
    """get the mutation of one pdb file"""
    
    if self.file:
        pass
    else:
        return None
    page = requests.get("https://www.rcsb.org/structure/" + self.id).text
    res = page[page.find("Mutation(s):")+26]
    if res == "Y":
        return "Yes"
    elif res == "N":
        return "No"
    else:
        return None

pdb.get_mutation = get_mutation

In [462]:
print(pdb("4lza").get_mutation())
print(pdb("4l00").get_mutation())
print(pdb("3kj1").get_mutation())
print(pdb("re43").get_mutation())

No
No
Yes
None

../pypdb/pypdb.py:504: UserWarning: Retrieval failed, returning None
  warnings.warn("Retrieval failed, returning None")
<ipython-input-453-da2cafa4f575>:10: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

<a id='74'></a>
## Extract Global Stoichiometry of each pdb file

In [463]:
def get_glo_sto(self):
    """get the Global Stoichiometry of each pdb file"""
    
    if self.file:
        pass
    else:
        return None
    page = requests.get("https://www.rcsb.org/structure/" + self.id).text
    res = page[page.find("Global Stoichiometry")+31 : page.find("&nbsp</span>", page.find("Global Stoichiometry"))]
    ress = res.replace("&nbsp<span style=\"word-wrap:break-word;\">", "")
    return ress

pdb.get_glo_sto = get_glo_sto

In [464]:
print(pdb("4lza").get_glo_sto())
print(pdb("4l00").get_glo_sto())
print(pdb("3kj1").get_glo_sto())
print(pdb("re43").get_glo_sto())

Homo 2-mer -A2
Monomer -A1
Hetero 2-mer -A1B1
None

<ipython-input-453-da2cafa4f575>:10: UserWarning: This pdb id file doesn't have a pdb format file
  warnings.warn("This pdb id file doesn't have a pdb format file")

## Add Mutation and Global Stoichiometry to the `general_table()`

In [341]:
def get_general_table(self):
    """get a general table of this pdb file"""
    
    if self.list == None:
        warnings.warn("This pdb id file doesn't have a pdb format file")
        return(pd.DataFrame({"PDB_ID": [self.id],
                       "Enzyme_Type": [None],
                       "Name": [None],
                       "Mutation": [None],
                       "Global Stoichiometry": [None],
                       "Organism_Name": [None],
                       "Organism_Taxid": [None],
                       "Ec_Number": [None],
                       "Strain": [None],
                       "Gene": [None],
                       "Resolution": [None],
                       "Chain_Id": [None],
                       "Fasta Sequence": [None],
                       "Num_Seqres": [None],
                       "Seqres": [None],
                       "Num_Missing": [None],
                       "Missing_Residue": [None],
                       "Missing_Id": [None]
                       }))
    
    chain_id = self.get_chain_id().split(", ")
    num_chain = len(chain_id)
    
    PDB_ID = [self.id] * num_chain
    Enzyme_Type = [self.get_enzyme_type()] * num_chain
    Name = [self.get_name()] * num_chain
    Organism_Name = [self.get_organism_name()] * num_chain
    Organism_Taxid = [self.get_organism_taxid()] * num_chain
    Ec_Number = [self.get_ec_number()] * num_chain
    Strain = [self.get_strain()] * num_chain
    Gene = [self.get_gene()] * num_chain
    Resolution = [self.get_resolution()] * num_chain
    Seqres = self.get_seqres()
    
    Num_Seqres = []
    Seqres_total = []
    for iid in chain_id:
        se = Seqres[Seqres[2] == iid].loc[:, 4:].values.tolist()
        a = []
        [a.extend(i) for i in se]
        Num_Seqres.append(len(a))
        Seqres_total.append(a)
    
    Num_Missing = []
    Missing = self.get_missing_residue()
    Missing_Residue = []
    Missing_Id = []
    
    if isinstance(Missing, str) or Missing is None:
        Num_Missing = [None] * num_chain
        Missing_Residue = [None] * num_chain
        Missing_Id = [None] * num_chain
    else:
        for iid in chain_id:
            se = Missing[Missing["CHAIN IDENTIFIER"] == iid]
            a = se["RESIDUE NAME"].values.tolist()
            b = se["SEQUENCE NUMBER"].values.tolist()
            Num_Missing.append(len(a))
            Missing_Residue.append(a)
            Missing_Id.append(b)
    
    fasta = []
    dic = self.get_fasta()
    for iid in chain_id:
        fasta.extend([v for k,v in dic.items() if iid in k])
        
    df = pd.DataFrame({"PDB_ID": PDB_ID,
                       "Enzyme_Type": Enzyme_Type,
                       "Name": Name,
                       "Mutation": [self.get_mutation()] * num_chain,
                       "Global Stoichiometry": [self.get_glo_sto()] * num_chain,
                       "Organism_Name": Organism_Name,
                       "Organism_Taxid": Organism_Taxid,
                       "Ec_Number": Ec_Number,
                       "Strain": Strain,
                       "Gene": Gene,
                       "Resolution": Resolution,
                       "Chain_Id": chain_id,
                       "Fasta Sequence": fasta,
                       "Num_Seqres": Num_Seqres,
                       "Seqres": Seqres_total,
                       "Num_Missing": Num_Missing,
                       "Missing_Residue": Missing_Residue,
                       "Missing_Id": Missing_Id
                       })
    return(df)

pdb.get_general_table = get_general_table

In [343]:
pdb("4lza").get_general_table()

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Fasta Sequence,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,4lza,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,No,Homo 2-mer -A2,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",1.84 ANGSTROMS,A,MHHHHHHSSGVDLGTENLYFQSMTLEEIKMMIREIPDFPKKGIKFK...,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",27,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -..."
1,4lza,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,No,Homo 2-mer -A2,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",1.84 ANGSTROMS,B,MHHHHHHSSGVDLGTENLYFQSMTLEEIKMMIREIPDFPKKGIKFK...,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",23,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -..."

In [344]:
pdb("3kj1").get_general_table()

<ipython-input-205-b4fe648fe448>:99: UserWarning: This pdb file doesn't have this field.
  warnings.warn("This pdb file doesn't have this field.")

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Fasta Sequence,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,3kj1,APOPTOSIS,INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION ...,Yes,Hetero 2-mer -A1B1,HOMO SAPIENS,9606,None,BL21(DE3)PLYSS,"BCL2L3, MCL-1, MCL1",1.95 ANGSTROMS,A,GSDELYRQSLEIISRYLREQATGAKDTKPMGRSGATSRKALETLRR...,169,"[GLY, SER, ASP, GLU, LEU, TYR, ARG, GLN, SER, ...",6,"[GLY, ASP, LEU, GLU, GLY, GLY]","[ 170, 323, 324, 325, 326, 327]"
1,3kj1,APOPTOSIS,INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION ...,Yes,Hetero 2-mer -A1B1,HOMO SAPIENS,9606,None,BL21(DE3)PLYSS,"BCL2L3, MCL-1, MCL1",1.95 ANGSTROMS,B,RPEIWAAQELRRIGDEFNAYYR,26,"[ARG, PRO, GLU, ILE, TRP, ALA, ALA, GLN, GLU, ...",0,[],[]

<a id='73'></a>
## Extract Entity ID

In [465]:
def get_entity_id(self):
    """get the entity id and belonging chains of each pdb file"""
    
    L = self.list
    dic = {}
    for i in range(len(L)):
        if re.search("^COMPND.*MOL_ID:", L[i]):
            j = i + 1
            while not re.search("^COMPND.*CHAIN:", L[j]):
                j += 1
            dic[L[i][L[i].find("MOL_ID: ")+8:L[i].find(";")]] = L[j][L[j].find("CHAIN: ")+7:L[j].find(";")]
    return dic

pdb.get_entity_id = get_entity_id

In [466]:
print(pdb("4lza").get_entity_id())
print(pdb("3kj1").get_entity_id())

{'1': 'A, B'}
{'1': 'A', '2': 'B'}

<a id='76'></a>
## Extract the number of sequence of each chain

In [467]:
def get_num_chain(self):
    """get the number of each chain in a pdb file"""
    
    if isinstance(self.get_seqres(), pd.DataFrame):
        pass
    else:
        return None
    L = self.get_seqres().loc[:, 2:3]
    dic = {}
    for i in range(L.shape[0]):
        dic[L.loc[i, 2]] = L.loc[i, 3]
    return dic

pdb.get_num_chain = get_num_chain

In [468]:
pdb("3kj1").get_num_chain()

{'A': '158', 'B': '22'}

### Add entity id into `general_table()`

In [488]:
def get_general_table(self):
    """get a general table of this pdb file"""
    
    if self.list == None:
        warnings.warn("This pdb id file doesn't have a pdb format file")
        return(pd.DataFrame({"PDB_ID": [self.id],
                       "Enzyme_Type": [None],
                       "Name": [None],
                       "Mutation": [None],
                       "Global Stoichiometry": [None],
                       "Organism_Name": [None],
                       "Organism_Taxid": [None],
                       "Ec_Number": [None],
                       "Strain": [None],
                       "Gene": [None],
                       "Resolution": [None],
                       "Chain_Id": [None],
                       "Fasta Sequence": [None],
                       "Entity ID": [None],
                       "Num_Seqres": [None],
                       "Seqres": [None],
                       "Num_Missing": [None],
                       "Missing_Residue": [None],
                       "Missing_Id": [None]
                       }))
    
    chain_id = self.get_chain_id().split(", ")
    num_chain = len(chain_id)
    
    PDB_ID = [self.id] * num_chain
    Enzyme_Type = [self.get_enzyme_type()] * num_chain
    Name = [self.get_name()] * num_chain
    Organism_Name = [self.get_organism_name()] * num_chain
    Organism_Taxid = [self.get_organism_taxid()] * num_chain
    Ec_Number = [self.get_ec_number()] * num_chain
    Strain = [self.get_strain()] * num_chain
    Gene = [self.get_gene()] * num_chain
    Resolution = [self.get_resolution()] * num_chain
    Seqres = self.get_seqres()
    
    Num_Seqres = []
    Seqres_total = []
    for iid in chain_id:
        se = Seqres[Seqres[2] == iid].loc[:, 4:].values.tolist()
        a = []
        [a.extend(i) for i in se]
        # Num_Seqres.append(len(a))
        Num_Seqres.append(self.get_num_chain()[iid])
        Seqres_total.append(a)
    
    Num_Missing = []
    Missing = self.get_missing_residue()
    Missing_Residue = []
    Missing_Id = []
    
    if isinstance(Missing, str) or Missing is None:
        Num_Missing = [None] * num_chain
        Missing_Residue = [None] * num_chain
        Missing_Id = [None] * num_chain
    else:
        for iid in chain_id:
            se = Missing[Missing["CHAIN IDENTIFIER"] == iid]
            a = se["RESIDUE NAME"].values.tolist()
            b = se["SEQUENCE NUMBER"].values.tolist()
            Num_Missing.append(len(a))
            Missing_Residue.append(a)
            Missing_Id.append(b)
    
    fasta = []
    dic = self.get_fasta()
    for iid in chain_id:
        fasta.extend([v for k,v in dic.items() if iid in k.lstrip("Chains ")])
    
    entity_id = []
    dic_1 = self.get_entity_id()
    for iid in chain_id:
        entity_id.extend([k for k, v in dic_1.items() if iid in v])
    
    df = pd.DataFrame({"PDB_ID": PDB_ID,
                       "Enzyme_Type": Enzyme_Type,
                       "Name": Name,
                       "Mutation": [self.get_mutation()] * num_chain,
                       "Global Stoichiometry": [self.get_glo_sto()] * num_chain,
                       "Organism_Name": Organism_Name,
                       "Organism_Taxid": Organism_Taxid,
                       "Ec_Number": Ec_Number,
                       "Strain": Strain,
                       "Gene": Gene,
                       "Resolution": Resolution,
                       "Chain_Id": chain_id,
                       "Fasta Sequence": fasta,
                       "Entity ID": entity_id,
                       "Num_Seqres": Num_Seqres,
                       "Seqres": Seqres_total,
                       "Num_Missing": Num_Missing,
                       "Missing_Residue": Missing_Residue,
                       "Missing_Id": Missing_Id
                       })
    return(df)

pdb.get_general_table = get_general_table

In [489]:
pdb("4lza").get_general_table()

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Fasta Sequence,Entity ID,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,4lza,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,No,Homo 2-mer -A2,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",1.84 ANGSTROMS,A,MHHHHHHSSGVDLGTENLYFQSMTLEEIKMMIREIPDFPKKGIKFK...,1,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",27,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -..."
1,4lza,TRANSFERASE,ADENINE PHOSPHORIBOSYLTRANSFERASE,No,Homo 2-mer -A2,THERMOANAEROBACTER PSEUDETHANOLICUS,340099,2.4.2.7,ATCC 33223,"166856274, APT, TETH39_1027",1.84 ANGSTROMS,B,MHHHHHHSSGVDLGTENLYFQSMTLEEIKMMIREIPDFPKKGIKFK...,1,195,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...",23,"[MSE, HIS, HIS, HIS, HIS, HIS, HIS, SER, SER, ...","[ -23, -22, -21, -20, -19, -18, -..."

In [490]:
pdb("3kj1").get_general_table()

<ipython-input-453-da2cafa4f575>:99: UserWarning: This pdb file doesn't have EC number field.
  warnings.warn("This pdb file doesn't have EC number field.")

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Fasta Sequence,Entity ID,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,3kj1,APOPTOSIS,INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION ...,Yes,Hetero 2-mer -A1B1,HOMO SAPIENS,9606,None,BL21(DE3)PLYSS,"BCL2L3, MCL-1, MCL1",1.95 ANGSTROMS,A,GSDELYRQSLEIISRYLREQATGAKDTKPMGRSGATSRKALETLRR...,1,158,"[GLY, SER, ASP, GLU, LEU, TYR, ARG, GLN, SER, ...",6,"[GLY, ASP, LEU, GLU, GLY, GLY]","[ 170, 323, 324, 325, 326, 327]"
1,3kj1,APOPTOSIS,INDUCED MYELOID LEUKEMIA CELL DIFFERENTIATION ...,Yes,Hetero 2-mer -A1B1,HOMO SAPIENS,9606,None,BL21(DE3)PLYSS,"BCL2L3, MCL-1, MCL1",1.95 ANGSTROMS,B,RPEIWAAQELRRIGDEFNAYYR,2,22,"[ARG, PRO, GLU, ILE, TRP, ALA, ALA, GLN, GLU, ...",0,[],[]

In [492]:
pdb("1BRS").get_general_table()

<ipython-input-453-da2cafa4f575>:123: UserWarning: This pdb file doesn't have this gene field.
  warnings.warn("This pdb file doesn't have this gene field.")

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Fasta Sequence,Entity ID,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,2.00 ANGSTROMS,A,AQVINTFDGVADYLQTYHKLPDNYITKSEAQALGWVASKGNLADVA...,1,110,"[ALA, GLN, VAL, ILE, ASN, THR, PHE, ASP, GLY, ...",2,"[ALA, GLN]","[ 1, 2]"
1,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,2.00 ANGSTROMS,B,AQVINTFDGVADYLQTYHKLPDNYITKSEAQALGWVASKGNLADVA...,1,110,"[ALA, GLN, VAL, ILE, ASN, THR, PHE, ASP, GLY, ...",0,[],[]
2,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,2.00 ANGSTROMS,C,AQVINTFDGVADYLQTYHKLPDNYITKSEAQALGWVASKGNLADVA...,1,110,"[ALA, GLN, VAL, ILE, ASN, THR, PHE, ASP, GLY, ...",2,"[ALA, GLN]","[ 1, 2]"
3,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,2.00 ANGSTROMS,D,KKAVINGEQIRSISDLHQTLKKELALPEYYGENLDALWDALTGWVE...,2,89,"[LYS, LYS, ALA, VAL, ILE, ASN, GLY, GLU, GLN, ...",2,"[GLU, ASN]","[ 64, 65]"
4,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,2.00 ANGSTROMS,E,KKAVINGEQIRSISDLHQTLKKELALPEYYGENLDALWDALTGWVE...,2,89,"[LYS, LYS, ALA, VAL, ILE, ASN, GLY, GLU, GLN, ...",3,"[LYS, GLU, ASN]","[ 1, 64, 65]"
5,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,2.00 ANGSTROMS,F,KKAVINGEQIRSISDLHQTLKKELALPEYYGENLDALWDALTGWVE...,2,89,"[LYS, LYS, ALA, VAL, ILE, ASN, GLY, GLU, GLN, ...",0,[],[]

In [493]:
pdb("6XOE").get_general_table()

<ipython-input-453-da2cafa4f575>:111: UserWarning: This pdb file doesn't have this strain field.
  warnings.warn("This pdb file doesn't have this strain field.")

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,Resolution,Chain_Id,Fasta Sequence,Entity ID,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,6XOE,TRANSFERASE,CALCIUM/CALMODULIN-DEPENDENT PROTEIN KINASE TY...,Yes,Hetero 2-mer -A1B1,HOMO SAPIENS,9606,2.7.11.17,None,"CAMK2A, CAMKA, KIAA0968",2.10 ANGSTROMS,A,TRFTEEYQLFEELGKGAFSVVRRCVKVLAGQEYAAKIINTKKLSAR...,1,268,"[THR, ARG, PHE, THR, GLU, GLU, TYR, GLN, LEU, ...",0,[],[]
1,6XOE,TRANSFERASE,CALCIUM/CALMODULIN-DEPENDENT PROTEIN KINASE TY...,Yes,Hetero 2-mer -A1B1,HOMO SAPIENS,9606,2.7.11.17,None,"CAMK2A, CAMKA, KIAA0968",2.10 ANGSTROMS,B,KAQKKNRNKLRRQHDYDTFVDL,2,22,"[LYS, ALA, GLN, LYS, LYS, ASN, ARG, ASN, LYS, ...",6,"[LYS, ALA, GLN, LYS, LYS, ASN]","[ 1289, 1290, 1291, 1292, 1293, 1294]"

<a id='72'></a>
## Extract yellow and grey box index of fasta sequence

### Extract yellow box index

In [498]:
import urllib

In [591]:
def get_part_mod_resi(self):
    """get the partially modeled residue index of fasta sequence of each chain in one pdb file"""
    
    pre = "{annotations(\
                   reference:PDB_INSTANCE,\
                   sources:PDB_INSTANCE,\
    queryId:\""
    suf = "\"\
  ){\
    target_id\
    features{\
      feature_id\
      type\
      provenance_source\
      description\
      name\
      feature_positions{\
        beg_seq_id\
        end_seq_id\
      }\
    }\
  }\
}"
    chain = [x for x in self.get_chain_id().split(", ")]
    pre_url = "https://1d-coordinates.rcsb.org/graphql?query="
    dic = {}
    for iid in chain:
        full_url = pre_url + urllib.parse.quote(pre + self.id.upper() + "." + iid + suf)
        text = requests.get(full_url).text
        start = text.find("partially modeled residue") + 50
        end = text.find("feature_id", start) - 3
        yellow = text[start:end]
        yellow_num = re.findall('\d+', yellow)
        yellow_num = [int(x) for x in yellow_num]
        yellow_num
        num = []
        for i in range(0, len(yellow_num), 2):
            num.append((yellow_num[i], yellow_num[i+1]))
        res = []
        for i,j in num:
            if i == j:
                res.append(i)
            elif i < j:
                res.extend([x for x in range(i, j+1)])
        dic[iid] = res
    return dic
pdb.get_part_mod_resi = get_part_mod_resi

In [596]:
pdb("1BRs").get_part_mod_resi()

{'A': [],
 'B': [],
 'C': [19, 22, 29, 31, 39, 45, 49, 67, 110],
 'D': [58, 60, 61],
 'E': [11, 18, 54, 58, 60, 61, 62],
 'F': [22, 28, 46, 64, 65, 89]}

### Extract grey box index

In [600]:
def get_unmod_resi(self):
    """get the unmodeled residue index of fasta sequence of each chain in one pdb file"""
    
    pre = "{annotations(\
                   reference:PDB_INSTANCE,\
                   sources:PDB_INSTANCE,\
    queryId:\""
    suf = "\"\
  ){\
    target_id\
    features{\
      feature_id\
      type\
      provenance_source\
      description\
      name\
      feature_positions{\
        beg_seq_id\
        end_seq_id\
      }\
    }\
  }\
}"
    chain = [x for x in self.get_chain_id().split(", ")]
    pre_url = "https://1d-coordinates.rcsb.org/graphql?query="
    dic = {}
    for iid in chain:
        full_url = pre_url + urllib.parse.quote(pre + self.id.upper() + "." + iid + suf)
        text = requests.get(full_url).text
        start = text.find("unmodeled residue") + 40
        end = text.find("feature_id", start) - 3
        yellow = text[start:end]
        yellow_num = re.findall('\d+', yellow)
        yellow_num = [int(x) for x in yellow_num]
        yellow_num
        num = []
        for i in range(0, len(yellow_num), 2):
            num.append((yellow_num[i], yellow_num[i+1]))
        res = []
        for i,j in num:
            if i == j:
                res.append(i)
            elif i < j:
                res.extend([x for x in range(i, j+1)])
        dic[iid] = res
    return dic
pdb.get_unmod_resi = get_unmod_resi

In [601]:
pdb("1brs").get_unmod_resi()

{'A': [1, 2], 'B': [], 'C': [1, 2], 'D': [64, 65], 'E': [1, 64, 65], 'F': []}

<a id='77'></a>
## Add this yellow and grey box index into the `general_table()` as two separate columns

In [609]:
def get_general_table(self):
    """get a general table of this pdb file"""
    
    if self.list == None:
        warnings.warn("This pdb id file doesn't have a pdb format file")
        return(pd.DataFrame({"PDB_ID": [self.id],
                       "Enzyme_Type": [None],
                       "Name": [None],
                       "Mutation": [None],
                       "Global Stoichiometry": [None],
                       "Organism_Name": [None],
                       "Organism_Taxid": [None],
                       "Ec_Number": [None],
                       "Strain": [None],
                       "Gene": [None],
                       "Resolution": [None],
                       "Chain_Id": [None],
                       "Fasta Sequence": [None],
                       "Partial Modeled Residue(yellow)": [None],
                       "Unmodeled Residue(grey)": [None],
                       "Entity ID": [None],
                       "Num_Seqres": [None],
                       "Seqres": [None],
                       "Num_Missing": [None],
                       "Missing_Residue": [None],
                       "Missing_Id": [None]
                       }))
    
    chain_id = self.get_chain_id().split(", ")
    num_chain = len(chain_id)
    
    PDB_ID = [self.id.upper()] * num_chain
    Enzyme_Type = [self.get_enzyme_type()] * num_chain
    Name = [self.get_name()] * num_chain
    Organism_Name = [self.get_organism_name()] * num_chain
    Organism_Taxid = [self.get_organism_taxid()] * num_chain
    Ec_Number = [self.get_ec_number()] * num_chain
    Strain = [self.get_strain()] * num_chain
    Gene = [self.get_gene()] * num_chain
    Resolution = [self.get_resolution()] * num_chain
    Seqres = self.get_seqres()
    
    Num_Seqres = []
    Seqres_total = []
    for iid in chain_id:
        se = Seqres[Seqres[2] == iid].loc[:, 4:].values.tolist()
        a = []
        [a.extend(i) for i in se]
        Num_Seqres.append(self.get_num_chain()[iid])
        Seqres_total.append(a)
    
    Num_Missing = []
    Missing = self.get_missing_residue()
    Missing_Residue = []
    Missing_Id = []
    
    if isinstance(Missing, str) or Missing is None:
        Num_Missing = [None] * num_chain
        Missing_Residue = [None] * num_chain
        Missing_Id = [None] * num_chain
    else:
        for iid in chain_id:
            se = Missing[Missing["CHAIN IDENTIFIER"] == iid]
            a = se["RESIDUE NAME"].values.tolist()
            b = se["SEQUENCE NUMBER"].values.tolist()
            Num_Missing.append(len(a))
            Missing_Residue.append(a)
            Missing_Id.append(b)
    
    fasta = []
    dic = self.get_fasta()
    for iid in chain_id:
        fasta.extend([v for k,v in dic.items() if iid in k.lstrip("Chains ")])
    
    entity_id = []
    dic_1 = self.get_entity_id()
    for iid in chain_id:
        entity_id.extend([k for k, v in dic_1.items() if iid in v])
    
    partial_index = []
    dic_2 = self.get_part_mod_resi()
    for iid in chain_id:
        partial_index.extend([v for k, v in dic_2.items() if iid in k])
    
    unmodel = []
    dic_3 = self.get_unmod_resi()
    for iid in chain_id:
        unmodel.extend([v for k, v in dic_3.items() if iid in k])
        
    df = pd.DataFrame({"PDB_ID": PDB_ID,
                       "Enzyme_Type": Enzyme_Type,
                       "Name": Name,
                       "Mutation": [self.get_mutation()] * num_chain,
                       "Global Stoichiometry": [self.get_glo_sto()] * num_chain,
                       "Organism_Name": Organism_Name,
                       "Organism_Taxid": Organism_Taxid,
                       "Ec_Number": Ec_Number,
                       "Strain": Strain,
                       "Gene": Gene,
                       "Resolution": Resolution,
                       "Chain_Id": chain_id,
                       "Fasta Sequence": fasta,
                       "Partial Modeled Residue(yellow)": partial_index,
                       "Unmodeled Residue(grey)": unmodel,
                       "Entity ID": entity_id,
                       "Num_Seqres": Num_Seqres,
                       "Seqres": Seqres_total,
                       "Num_Missing": Num_Missing,
                       "Missing_Residue": Missing_Residue,
                       "Missing_Id": Missing_Id
                       })
    return(df)

pdb.get_general_table = get_general_table

In [610]:
pdb("1brs").get_general_table()

<ipython-input-453-da2cafa4f575>:123: UserWarning: This pdb file doesn't have this gene field.
  warnings.warn("This pdb file doesn't have this gene field.")

,PDB_ID,Enzyme_Type,Name,Mutation,Global Stoichiometry,Organism_Name,Organism_Taxid,Ec_Number,Strain,Gene,...,Chain_Id,Fasta Sequence,Partial Modeled Residue(yellow),Unmodeled Residue(grey),Entity ID,Num_Seqres,Seqres,Num_Missing,Missing_Residue,Missing_Id
0,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,...,A,AQVINTFDGVADYLQTYHKLPDNYITKSEAQALGWVASKGNLADVA...,[],"[1, 2]",1,110,"[ALA, GLN, VAL, ILE, ASN, THR, PHE, ASP, GLY, ...",2,"[ALA, GLN]","[ 1, 2]"
1,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,...,B,AQVINTFDGVADYLQTYHKLPDNYITKSEAQALGWVASKGNLADVA...,[],[],1,110,"[ALA, GLN, VAL, ILE, ASN, THR, PHE, ASP, GLY, ...",0,[],[]
2,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,...,C,AQVINTFDGVADYLQTYHKLPDNYITKSEAQALGWVASKGNLADVA...,"[19, 22, 29, 31, 39, 45, 49, 67, 110]","[1, 2]",1,110,"[ALA, GLN, VAL, ILE, ASN, THR, PHE, ASP, GLY, ...",2,"[ALA, GLN]","[ 1, 2]"
3,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,...,D,KKAVINGEQIRSISDLHQTLKKELALPEYYGENLDALWDALTGWVE...,"[58, 60, 61]","[64, 65]",2,89,"[LYS, LYS, ALA, VAL, ILE, ASN, GLY, GLU, GLN, ...",2,"[GLU, ASN]","[ 64, 65]"
4,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,...,E,KKAVINGEQIRSISDLHQTLKKELALPEYYGENLDALWDALTGWVE...,"[11, 18, 54, 58, 60, 61, 62]","[1, 64, 65]",2,89,"[LYS, LYS, ALA, VAL, ILE, ASN, GLY, GLU, GLN, ...",3,"[LYS, GLU, ASN]","[ 1, 64, 65]"
5,1BRS,ENDONUCLEASE,BARNASE,No,Hetero 2-mer -A1B1,BACILLUS AMYLOLIQUEFACIENS,1390,3.1.27.-,BL21-(PLYSE) (PML2BS) CELLS,None,...,F,KKAVINGEQIRSISDLHQTLKKELALPEYYGENLDALWDALTGWVE...,"[22, 28, 46, 64, 65, 89]",[],2,89,"[LYS, LYS, ALA, VAL, ILE, ASN, GLY, GLU, GLN, ...",0,[],[]